-- Initial PostgreSQL 18 schema: accounts. Generated from disposable metadata.
CREATE TABLE "account_consents" (
  app_user_id TEXT NOT NULL,
  policy_kind TEXT NOT NULL,
  version TEXT NOT NULL,
  accepted_at TEXT NOT NULL,
  PRIMARY KEY(app_user_id,policy_kind,version)
);

CREATE TABLE "account_direct_messages" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id BIGINT NOT NULL,
  recipient_user_id BIGINT NOT NULL,
  body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 2000),
  created_at TEXT NOT NULL,
  read_at TEXT,
  CHECK(sender_user_id <> recipient_user_id)
);

CREATE TABLE "account_metadata" (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE "account_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "display_name" TEXT,
  "account_type" TEXT,
  "ban_status" TEXT,
  "identity_provider" TEXT,
  "identity_subject" TEXT,
  "location_country" TEXT,
  "location_region" TEXT,
  "bio" TEXT,
  "date_of_birth" TEXT,
  "avatar_storage_path" TEXT,
  "avatar_original_filename" TEXT,
  "avatar_mime_type" TEXT,
  "birth_visibility" TEXT,
  "residence_visibility" TEXT,
  "bio_visibility" TEXT,
  "avatar_visibility" TEXT,
  "theme" TEXT,
  "theme_override" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "app_user_id" TEXT,
  role TEXT NOT NULL DEFAULT 'member',
  disabled BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE "account_user_follows" (
  follower_user_id BIGINT NOT NULL,
  followed_user_id BIGINT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (follower_user_id, followed_user_id),
  CHECK (follower_user_id <> followed_user_id)
);

CREATE TABLE "identity_links" (
  issuer TEXT NOT NULL,
  tenant TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL,
  app_user_id TEXT NOT NULL,
  PRIMARY KEY(issuer,tenant,subject)
);

CREATE TABLE "local_sessions" (
  token_hash TEXT PRIMARY KEY,
  app_user_id TEXT NOT NULL,
  expires_at DOUBLE PRECISION NOT NULL
);

CREATE UNIQUE INDEX account_uuid ON account_records(app_user_id);

ALTER TABLE "account_consents" ADD CONSTRAINT "fk_account_consents_0" FOREIGN KEY ("app_user_id") REFERENCES "account_records" ("app_user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "account_direct_messages" ADD CONSTRAINT "fk_account_direct_messages_0" FOREIGN KEY ("recipient_user_id") REFERENCES "account_records" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "account_direct_messages" ADD CONSTRAINT "fk_account_direct_messages_1" FOREIGN KEY ("sender_user_id") REFERENCES "account_records" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "account_user_follows" ADD CONSTRAINT "fk_account_user_follows_0" FOREIGN KEY ("followed_user_id") REFERENCES "account_records" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "account_user_follows" ADD CONSTRAINT "fk_account_user_follows_1" FOREIGN KEY ("follower_user_id") REFERENCES "account_records" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "identity_links" ADD CONSTRAINT "fk_identity_links_0" FOREIGN KEY ("app_user_id") REFERENCES "account_records" ("app_user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "local_sessions" ADD CONSTRAINT "fk_local_sessions_0" FOREIGN KEY ("app_user_id") REFERENCES "account_records" ("app_user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Preserve identity reservations independently of content recovery.
CREATE FUNCTION ygc_guard_account_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Disable accounts instead of deleting their identity registry';
  END IF;
  IF NEW.id IS DISTINCT FROM OLD.id OR NEW.app_user_id IS DISTINCT FROM OLD.app_user_id THEN
    RAISE EXCEPTION 'Account identity is immutable';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER immutable_account_identity BEFORE UPDATE OR DELETE ON account_records
FOR EACH ROW EXECUTE FUNCTION ygc_guard_account_identity();
