-- Durable account changes; applied explicitly by the schema owner.
ALTER TABLE account_records ALTER COLUMN app_user_id SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN display_name SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN account_type SET DEFAULT 'user';
ALTER TABLE account_records ALTER COLUMN ban_status SET DEFAULT 'normal';
ALTER TABLE account_records ALTER COLUMN birth_visibility SET DEFAULT 'Private';
ALTER TABLE account_records ALTER COLUMN residence_visibility SET DEFAULT 'Private';
ALTER TABLE account_records ALTER COLUMN bio_visibility SET DEFAULT 'Public';
ALTER TABLE account_records ALTER COLUMN avatar_visibility SET DEFAULT 'Public';
ALTER TABLE account_records ALTER COLUMN theme SET DEFAULT 'dark_default';
ALTER TABLE account_records ALTER COLUMN account_type SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN ban_status SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN birth_visibility SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN residence_visibility SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN bio_visibility SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN avatar_visibility SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN theme SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE account_records ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE account_records ADD CONSTRAINT account_ban_status CHECK(ban_status IN ('normal','silent_ban','ban'));
ALTER TABLE account_records ADD COLUMN projection_version BIGINT NOT NULL DEFAULT 1 CHECK(projection_version>0);
ALTER TABLE account_records ADD CONSTRAINT account_role CHECK(role IN ('member','admin'));
ALTER TABLE account_records ADD CONSTRAINT account_disabled CHECK(disabled IN (0,1));
CREATE TABLE account_projection_outbox (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id BIGINT NOT NULL REFERENCES account_records(id),
 app_user_id TEXT NOT NULL,
 revision BIGINT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 delivered_at TIMESTAMPTZ,
 UNIQUE(account_id,revision)
);
CREATE INDEX pending_account_projection ON account_projection_outbox(id) WHERE delivered_at IS NULL;
CREATE FUNCTION ygc_account_revision() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 NEW.projection_version := CASE WHEN TG_OP='INSERT' THEN 1 ELSE OLD.projection_version+1 END;
 RETURN NEW;
END $$;
CREATE TRIGGER account_revision BEFORE INSERT OR UPDATE ON account_records
 FOR EACH ROW EXECUTE FUNCTION ygc_account_revision();
CREATE FUNCTION ygc_queue_account_projection() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 INSERT INTO account_projection_outbox(account_id,app_user_id,revision)
 VALUES(NEW.id,NEW.app_user_id,NEW.projection_version);
 RETURN NEW;
END $$;
CREATE TRIGGER queue_account_projection AFTER INSERT OR UPDATE ON account_records
 FOR EACH ROW EXECUTE FUNCTION ygc_queue_account_projection();
-- Existing accounts are queued without overwriting any profile or authority.
INSERT INTO account_projection_outbox(account_id,app_user_id,revision)
 SELECT id,app_user_id,projection_version FROM account_records;
CREATE FUNCTION ygc_guard_identity_link() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN
  RAISE EXCEPTION 'Identity reassignment requires an explicit account-link migration';
 END IF;
 IF NEW.issuer IS DISTINCT FROM OLD.issuer OR NEW.tenant IS DISTINCT FROM OLD.tenant
    OR NEW.subject IS DISTINCT FROM OLD.subject OR NEW.app_user_id IS DISTINCT FROM OLD.app_user_id THEN
  RAISE EXCEPTION 'Identity reassignment requires an explicit account-link migration';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER immutable_identity_link BEFORE UPDATE OR DELETE ON identity_links
 FOR EACH ROW EXECUTE FUNCTION ygc_guard_identity_link();
