-- Initial PostgreSQL 18 schema: authentication. Generated from disposable metadata.
CREATE TABLE "events" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision TEXT NOT NULL,
  at TEXT NOT NULL,
  kind TEXT NOT NULL,
  note TEXT NOT NULL
);

CREATE TABLE "jobs" (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id TEXT NOT NULL,
  revision TEXT UNIQUE NOT NULL,
  serial TEXT NOT NULL,
  challenge TEXT NOT NULL,
  images TEXT NOT NULL,
  image_meta TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TEXT NOT NULL,
  started_at TEXT,
  completed_at TEXT,
  attempts BIGINT NOT NULL DEFAULT 0,
  lease_token TEXT,
  lease_until DOUBLE PRECISION,
  error TEXT,
  received TEXT,
  result TEXT,
  report TEXT,
  prompt_version TEXT NOT NULL
);

CREATE TABLE "settings" (
  name TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

ALTER TABLE "events" ADD CONSTRAINT "fk_events_0" FOREIGN KEY ("revision") REFERENCES "jobs" ("revision") ON UPDATE NO ACTION ON DELETE CASCADE;
