-- Initial PostgreSQL 18 schema: chronicle. Generated from disposable metadata.
CREATE TABLE "acquire_application_events" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision TEXT NOT NULL,
  at TEXT NOT NULL,
  kind TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "acquire_applications" (
  request_kind TEXT NOT NULL DEFAULT 'acquire',
  listing_payload TEXT,
  seen_event_id BIGINT NOT NULL DEFAULT 0,
  revision TEXT PRIMARY KEY,
  applicant_id BIGINT NOT NULL,
  individual_id BIGINT,
  original_individual_id BIGINT NOT NULL,
  serial TEXT NOT NULL,
  challenge TEXT NOT NULL,
  expires_at DOUBLE PRECISION NOT NULL,
  created_at TEXT NOT NULL,
  submitted_at TEXT,
  started_at TEXT,
  completed_at TEXT,
  acquisition_date TEXT,
  body TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  images TEXT,
  image_meta TEXT,
  reference_source TEXT,
  product_details TEXT,
  product_observations TEXT,
  attempts BIGINT NOT NULL DEFAULT 0,
  lease_token TEXT,
  lease_until DOUBLE PRECISION,
  error TEXT,
  received TEXT,
  result TEXT,
  report TEXT,
  prompt_version TEXT NOT NULL,
  claim_id BIGINT UNIQUE
);

CREATE TABLE "claim_admin_actions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  individual_id BIGINT NOT NULL,
  action TEXT NOT NULL,
  previous_verification TEXT,
  actor TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "claim_evidence" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  media_asset_id BIGINT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(claim_id, media_asset_id)
);

CREATE TABLE "claim_identity_items" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  field_name TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE "claim_listing_items" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  field_name TEXT NOT NULL,
  value_text TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE(claim_id, field_name)
);

CREATE TABLE "claim_responses" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  responder_user_id BIGINT NOT NULL,
  stance TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(claim_id, responder_user_id)
);

CREATE TABLE "claim_source_evidence" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  evidence_type TEXT NOT NULL CHECK (evidence_type IN ('marketplace_listing', 'acquisition_date')),
  source_site TEXT,
  source_listing_id TEXT,
  source_url TEXT,
  captured_at TEXT,
  effective_date TEXT,
  date_basis TEXT,
  payload_json TEXT,
  legacy_observation_id BIGINT UNIQUE,
  created_at TEXT NOT NULL
);

CREATE TABLE "claim_spec_items" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  field_name TEXT NOT NULL,
  value_text TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "claim_specification_source" (
  claim_id BIGINT PRIMARY KEY,
  source_site TEXT NOT NULL,
  source_listing_id TEXT NOT NULL,
  source_url TEXT,
  captured_at TEXT NOT NULL,
  extracted_json TEXT NOT NULL,
  UNIQUE(source_site, source_listing_id, claim_id)
);

CREATE TABLE "claim_transfer_acceptance" (
  claim_id BIGINT PRIMARY KEY,
  accepted_by_user_id BIGINT NOT NULL,
  accepted_at TEXT NOT NULL,
  current_owner_user_id BIGINT NOT NULL
);

CREATE TABLE "claim_transfers" (
  claim_id BIGINT PRIMARY KEY,
  from_user_id BIGINT NOT NULL,
  to_user_id BIGINT NOT NULL,
  state TEXT NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','accepted','declined','cancelled')),
  created_at TEXT NOT NULL,
  resolved_at TEXT,
  CHECK(from_user_id<>to_user_id)
);

CREATE TABLE "claim_votes" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  vote TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(claim_id, user_id)
);

CREATE TABLE "claims" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id BIGINT NOT NULL,
  observation_id BIGINT,
  author_user_id BIGINT NOT NULL,
  claim_type TEXT NOT NULL,
  field_name TEXT,
  value_text TEXT,
  specification_kind TEXT,
  ownership_kind TEXT,
  ownership_source TEXT,
  ownership_pair_id TEXT,
  previous_owner_text TEXT,
  body TEXT,
  target_claim_id BIGINT,
  occurred_at TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  verification_status TEXT NOT NULL DEFAULT 'positive',
  admin_verification BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE "crawl_candidates" (
  source_site TEXT NOT NULL,
  source_listing_id TEXT NOT NULL,
  claim_json TEXT NOT NULL,
  provenance_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  reason TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(source_site, source_listing_id)
);

CREATE TABLE "crawl_detail_cache" (
  source_site TEXT NOT NULL,
  source_listing_id TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  fetched_at TEXT NOT NULL,
  PRIMARY KEY(source_site, source_listing_id)
);

CREATE TABLE "crawl_listing_cache" (
  source_site TEXT NOT NULL,
  source_listing_id TEXT NOT NULL,
  status TEXT NOT NULL,
  checked_at TEXT NOT NULL,
  recheck_after TEXT NOT NULL,
  PRIMARY KEY(source_site, source_listing_id)
);

CREATE TABLE "crawl_listing_checks" (
  source_site TEXT NOT NULL,
  source_listing_id TEXT NOT NULL,
  api_url TEXT,
  checked_at TEXT,
  missing_since TEXT,
  status TEXT NOT NULL DEFAULT 'unknown',
  PRIMARY KEY(source_site, source_listing_id)
);

CREATE TABLE "crawl_programs" (
  source_site TEXT NOT NULL,
  category TEXT NOT NULL,
  year_min BIGINT NOT NULL,
  year_max BIGINT NOT NULL,
  page_url TEXT,
  pending_json TEXT,
  next_url TEXT,
  processed BIGINT NOT NULL DEFAULT 0,
  observations_created BIGINT NOT NULL DEFAULT 0,
  finished BIGINT NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(source_site, category, year_min, year_max)
);

CREATE TABLE "crawl_runs" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_site TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  pages_discovered BIGINT DEFAULT 0,
  pages_fetched BIGINT DEFAULT 0,
  observations_created BIGINT DEFAULT 0,
  status TEXT NOT NULL,
  error_message TEXT,
  category TEXT,
  year_min BIGINT,
  year_max BIGINT,
  phase TEXT,
  counts_json TEXT,
  updated_at TEXT
);

CREATE TABLE "crawl_unregistered_records" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_site TEXT NOT NULL,
  source_listing_id TEXT NOT NULL,
  source_url TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  reason TEXT NOT NULL,
  payload_json TEXT NOT NULL CHECK(pg_input_is_valid(payload_json, 'json')),
  created_at TEXT NOT NULL,
  UNIQUE(source_site, source_listing_id)
);

CREATE TABLE "direct_messages" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id BIGINT NOT NULL,
  recipient_user_id BIGINT NOT NULL,
  body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 2000),
  created_at TEXT NOT NULL,
  read_at TEXT,
  CHECK(sender_user_id <> recipient_user_id)
);

CREATE TABLE "individual_resolution_actions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id BIGINT NOT NULL,
  keep_id BIGINT NOT NULL,
  action TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "individuals" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manufacturer TEXT NOT NULL,
  model TEXT,
  finish TEXT,
  year TEXT,
  serial_number TEXT,
  location_country TEXT,
  location_region TEXT,
  current_owner_name TEXT,
  current_owner_type TEXT,
  current_owner_user_id BIGINT,
  current_owner_source_url TEXT,
  normalized_manufacturer TEXT NOT NULL,
  normalized_model TEXT,
  normalized_serial TEXT,
  representative_media_asset_id BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(normalized_manufacturer, normalized_model, normalized_serial)
);

CREATE TABLE "legacy_crawl_archive" (
  legacy_observation_id BIGINT PRIMARY KEY,
  payload_json TEXT NOT NULL CHECK(pg_input_is_valid(payload_json, 'json')),
  payload_sha256 TEXT NOT NULL,
  archived_at TEXT NOT NULL
);

CREATE TABLE "media_assets" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id BIGINT NOT NULL,
  uploader_user_id BIGINT NOT NULL,
  media_type TEXT NOT NULL DEFAULT 'image',
  storage_path TEXT NOT NULL,
  original_filename TEXT,
  mime_type TEXT,
  captured_at TEXT,
  caption TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE "notifications" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id BIGINT NOT NULL,
  actor_user_id BIGINT,
  notification_type TEXT NOT NULL,
  individual_id BIGINT,
  claim_id BIGINT,
  title TEXT NOT NULL,
  body TEXT,
  is_read BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  read_at TEXT
);

CREATE TABLE "observations" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id BIGINT,
  manufacturer TEXT,
  model TEXT,
  finish TEXT,
  year TEXT,
  serial_number TEXT,
  owner_name TEXT,
  owner_type TEXT,
  owner_profile_url TEXT,
  location_country TEXT,
  location_region TEXT,
  location_source TEXT,
  seller TEXT,
  event_type TEXT NOT NULL DEFAULT 'listing',
  actor_user_id BIGINT,
  occurred_at TEXT,
  source_site TEXT NOT NULL,
  source_url TEXT NOT NULL,
  image_url TEXT,
  source_listing_id TEXT,
  observed_at TEXT NOT NULL,
  listing_date TEXT,
  title TEXT,
  raw_text TEXT,
  serial_confidence DOUBLE PRECISION,
  extraction_version TEXT,
  created_at TEXT NOT NULL,
  UNIQUE(source_site, source_listing_id)
);

CREATE TABLE "ownership_declines" (
  claim_id BIGINT PRIMARY KEY,
  owner_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  created_at TEXT NOT NULL,
  acknowledged_at TEXT
);

CREATE TABLE "ownership_dispute_claims" (
  dispute_id BIGINT NOT NULL,
  claim_id BIGINT NOT NULL UNIQUE,
  applicant_id BIGINT NOT NULL,
  PRIMARY KEY(dispute_id,claim_id)
);

CREATE TABLE "ownership_dispute_events" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispute_id BIGINT NOT NULL,
  actor_id BIGINT,
  kind TEXT NOT NULL,
  note TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "ownership_dispute_evidence" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispute_id BIGINT NOT NULL,
  claim_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  explanation TEXT NOT NULL,
  summary TEXT NOT NULL,
  published_summary TEXT,
  published_at TEXT,
  filename TEXT,
  content_type TEXT,
  content BYTEA,
  created_at TEXT NOT NULL
);

CREATE TABLE "ownership_dispute_round_evidence" (
  evidence_id BIGINT PRIMARY KEY,
  round_id BIGINT NOT NULL
);

CREATE TABLE "ownership_dispute_round_parties" (
  round_id BIGINT NOT NULL,
  claim_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  submitted_at TEXT,
  PRIMARY KEY(round_id,claim_id,user_id)
);

CREATE TABLE "ownership_dispute_rounds" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispute_id BIGINT NOT NULL,
  number BIGINT NOT NULL,
  phase TEXT NOT NULL CHECK(phase IN ('collecting','reviewing')),
  request_reason TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  UNIQUE(dispute_id,number)
);

CREATE TABLE "ownership_disputes" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  individual_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,
  locked_owner_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved','resolving','checking')),
  version BIGINT NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  decision TEXT,
  reason TEXT,
  winner_id BIGINT
);

CREATE TABLE "user_admin_actions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  previous_ban_status TEXT NOT NULL,
  ban_status TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE "user_favorites" (
  user_id BIGINT NOT NULL,
  individual_id BIGINT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY(user_id, individual_id)
);

CREATE TABLE "user_follows" (
  follower_user_id BIGINT NOT NULL,
  followed_user_id BIGINT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (follower_user_id, followed_user_id),
  CHECK (follower_user_id <> followed_user_id)
);

CREATE TABLE "user_guitars" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  individual_id BIGINT NOT NULL,
  ownership_status TEXT NOT NULL DEFAULT 'current_owner',
  display_order BIGINT,
  acquired_at TEXT,
  released_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(user_id, individual_id)
);

CREATE TABLE "users" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name TEXT NOT NULL,
  account_type TEXT NOT NULL DEFAULT 'user',
  ban_status TEXT NOT NULL DEFAULT 'normal' CHECK (ban_status IN ('normal','silent_ban','ban')),
  identity_provider TEXT,
  identity_subject TEXT,
  location_country TEXT,
  location_region TEXT,
  bio TEXT,
  date_of_birth TEXT,
  avatar_storage_path TEXT,
  avatar_original_filename TEXT,
  avatar_mime_type TEXT,
  birth_visibility TEXT NOT NULL DEFAULT 'Private',
  residence_visibility TEXT NOT NULL DEFAULT 'Private',
  bio_visibility TEXT NOT NULL DEFAULT 'Public',
  avatar_visibility TEXT NOT NULL DEFAULT 'Public',
  signature_individual_id BIGINT,
  theme TEXT NOT NULL DEFAULT 'dark_default',
  theme_override TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  app_user_id TEXT
);

CREATE UNIQUE INDEX idx_acquire_open_application
 ON acquire_applications(applicant_id,individual_id)
 WHERE status IN ('draft','pending','processing','error');

CREATE INDEX idx_claim_evidence_claim_id ON claim_evidence(claim_id);

CREATE INDEX idx_claim_identity_items_claim_id ON claim_identity_items(claim_id);

CREATE INDEX idx_claim_listing_items_claim_id ON claim_listing_items(claim_id);

CREATE INDEX idx_claim_responses_claim_id ON claim_responses(claim_id);

CREATE INDEX idx_claim_source_evidence_claim
 ON claim_source_evidence(claim_id);

CREATE UNIQUE INDEX idx_claim_source_listing_unique
 ON claim_source_evidence(source_site, source_listing_id)
 WHERE source_site IS NOT NULL AND source_listing_id IS NOT NULL;

CREATE INDEX idx_claim_spec_items_claim_id ON claim_spec_items(claim_id);

CREATE INDEX idx_claim_transfers_to_state ON claim_transfers(to_user_id,state);

CREATE INDEX idx_claim_votes_claim_id ON claim_votes(claim_id);

CREATE INDEX idx_claims_individual_id ON claims(individual_id);

CREATE INDEX idx_claims_observation_id ON claims(observation_id);

CREATE INDEX idx_claims_target_claim_id
            ON claims(target_claim_id)
            ;

CREATE INDEX idx_crawl_candidates_status
ON crawl_candidates(source_site, status);

CREATE INDEX idx_crawl_listing_cache_recheck_after
ON crawl_listing_cache(source_site, recheck_after);

CREATE INDEX idx_dm_recipient_read ON direct_messages(recipient_user_id,read_at,id);

CREATE INDEX idx_dm_sender_recipient ON direct_messages(sender_user_id,recipient_user_id,id);

CREATE INDEX idx_media_assets_individual_id ON media_assets(individual_id);

CREATE INDEX idx_notifications_recipient_read_created
ON notifications(recipient_user_id, is_read, created_at DESC);

CREATE INDEX idx_observations_individual_id ON observations(individual_id);

CREATE INDEX idx_observations_source_url ON observations(source_url);

CREATE INDEX idx_user_follows_followed ON user_follows(followed_user_id, follower_user_id);

CREATE INDEX idx_user_guitars_individual_id ON user_guitars(individual_id);

CREATE INDEX idx_user_guitars_user_id ON user_guitars(user_id);

CREATE UNIQUE INDEX idx_users_identity_subject ON users(identity_provider, identity_subject) WHERE identity_subject IS NOT NULL;

CREATE UNIQUE INDEX one_open_ownership_dispute
 ON ownership_disputes(individual_id) WHERE status='open';

ALTER TABLE "acquire_application_events" ADD CONSTRAINT "fk_acquire_application_events_0" FOREIGN KEY ("revision") REFERENCES "acquire_applications" ("revision") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "acquire_applications" ADD CONSTRAINT "fk_acquire_applications_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "acquire_applications" ADD CONSTRAINT "fk_acquire_applications_1" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "claim_evidence" ADD CONSTRAINT "fk_claim_evidence_0" FOREIGN KEY ("media_asset_id") REFERENCES "media_assets" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_evidence" ADD CONSTRAINT "fk_claim_evidence_1" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_identity_items" ADD CONSTRAINT "fk_claim_identity_items_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_listing_items" ADD CONSTRAINT "fk_claim_listing_items_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_responses" ADD CONSTRAINT "fk_claim_responses_0" FOREIGN KEY ("responder_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_responses" ADD CONSTRAINT "fk_claim_responses_1" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_source_evidence" ADD CONSTRAINT "fk_claim_source_evidence_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_spec_items" ADD CONSTRAINT "fk_claim_spec_items_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_specification_source" ADD CONSTRAINT "fk_claim_specification_source_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_transfer_acceptance" ADD CONSTRAINT "fk_claim_transfer_acceptance_0" FOREIGN KEY ("claim_id") REFERENCES "claim_transfers" ("claim_id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_transfers" ADD CONSTRAINT "fk_claim_transfers_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_votes" ADD CONSTRAINT "fk_claim_votes_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claim_votes" ADD CONSTRAINT "fk_claim_votes_1" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claims" ADD CONSTRAINT "fk_claims_0" FOREIGN KEY ("target_claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "claims" ADD CONSTRAINT "fk_claims_1" FOREIGN KEY ("author_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "claims" ADD CONSTRAINT "fk_claims_2" FOREIGN KEY ("observation_id") REFERENCES "observations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "claims" ADD CONSTRAINT "fk_claims_3" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "direct_messages" ADD CONSTRAINT "fk_direct_messages_0" FOREIGN KEY ("recipient_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "direct_messages" ADD CONSTRAINT "fk_direct_messages_1" FOREIGN KEY ("sender_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "media_assets" ADD CONSTRAINT "fk_media_assets_0" FOREIGN KEY ("uploader_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "media_assets" ADD CONSTRAINT "fk_media_assets_1" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_0" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_1" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_2" FOREIGN KEY ("actor_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "notifications" ADD CONSTRAINT "fk_notifications_3" FOREIGN KEY ("recipient_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "observations" ADD CONSTRAINT "fk_observations_0" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_declines" ADD CONSTRAINT "fk_ownership_declines_0" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_declines" ADD CONSTRAINT "fk_ownership_declines_1" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "ownership_dispute_claims" ADD CONSTRAINT "fk_ownership_dispute_claims_0" FOREIGN KEY ("applicant_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_claims" ADD CONSTRAINT "fk_ownership_dispute_claims_1" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_claims" ADD CONSTRAINT "fk_ownership_dispute_claims_2" FOREIGN KEY ("dispute_id") REFERENCES "ownership_disputes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_events" ADD CONSTRAINT "fk_ownership_dispute_events_0" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_events" ADD CONSTRAINT "fk_ownership_dispute_events_1" FOREIGN KEY ("dispute_id") REFERENCES "ownership_disputes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_evidence" ADD CONSTRAINT "fk_ownership_dispute_evidence_0" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_evidence" ADD CONSTRAINT "fk_ownership_dispute_evidence_1" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_evidence" ADD CONSTRAINT "fk_ownership_dispute_evidence_2" FOREIGN KEY ("dispute_id") REFERENCES "ownership_disputes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_round_evidence" ADD CONSTRAINT "fk_ownership_dispute_round_evidence_0" FOREIGN KEY ("round_id") REFERENCES "ownership_dispute_rounds" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_round_evidence" ADD CONSTRAINT "fk_ownership_dispute_round_evidence_1" FOREIGN KEY ("evidence_id") REFERENCES "ownership_dispute_evidence" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_round_parties" ADD CONSTRAINT "fk_ownership_dispute_round_parties_0" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_round_parties" ADD CONSTRAINT "fk_ownership_dispute_round_parties_1" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_round_parties" ADD CONSTRAINT "fk_ownership_dispute_round_parties_2" FOREIGN KEY ("round_id") REFERENCES "ownership_dispute_rounds" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_dispute_rounds" ADD CONSTRAINT "fk_ownership_dispute_rounds_0" FOREIGN KEY ("dispute_id") REFERENCES "ownership_disputes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_disputes" ADD CONSTRAINT "fk_ownership_disputes_0" FOREIGN KEY ("winner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_disputes" ADD CONSTRAINT "fk_ownership_disputes_1" FOREIGN KEY ("locked_owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_disputes" ADD CONSTRAINT "fk_ownership_disputes_2" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "ownership_disputes" ADD CONSTRAINT "fk_ownership_disputes_3" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "user_favorites" ADD CONSTRAINT "fk_user_favorites_0" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "user_favorites" ADD CONSTRAINT "fk_user_favorites_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "user_follows" ADD CONSTRAINT "fk_user_follows_0" FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "user_follows" ADD CONSTRAINT "fk_user_follows_1" FOREIGN KEY ("follower_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "user_guitars" ADD CONSTRAINT "fk_user_guitars_0" FOREIGN KEY ("individual_id") REFERENCES "individuals" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "user_guitars" ADD CONSTRAINT "fk_user_guitars_1" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- Equivalent to SQLite dispute locks; ordinary/admin paths must respect them.
CREATE FUNCTION ygc_guard_dispute_claim() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.claim_type IN ('ownership','listing','identity_correction') AND EXISTS
      (SELECT 1 FROM ownership_disputes WHERE individual_id=NEW.individual_id AND status='open') THEN
      RAISE EXCEPTION 'Ownership dispute lock: new ownership Claims are paused';
    END IF;
    RETURN NEW;
  END IF;
  IF (OLD.claim_type IN ('ownership','listing','identity_correction') AND EXISTS
      (SELECT 1 FROM ownership_disputes WHERE individual_id=OLD.individual_id AND status='open'))
    OR EXISTS (SELECT 1 FROM ownership_dispute_claims dc JOIN ownership_disputes d ON d.id=dc.dispute_id
      WHERE dc.claim_id=OLD.id AND d.status NOT IN ('resolving','checking')) THEN
    RAISE EXCEPTION 'Ownership dispute lock: use dispute reconsideration';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER dispute_claim_guard BEFORE INSERT OR UPDATE OR DELETE ON claims
FOR EACH ROW EXECUTE FUNCTION ygc_guard_dispute_claim();
CREATE FUNCTION ygc_guard_dispute_individual() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF EXISTS (SELECT 1 FROM ownership_disputes WHERE individual_id=OLD.id) THEN
      RAISE EXCEPTION 'Ownership dispute lock: retain the dispute history';
    END IF;
    RETURN OLD;
  END IF;
  IF EXISTS (SELECT 1 FROM ownership_disputes WHERE individual_id=OLD.id AND status='open'
      AND NEW.current_owner_user_id IS DISTINCT FROM locked_owner_id) THEN
    RAISE EXCEPTION 'Ownership dispute lock: Current Owner is frozen';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER dispute_owner_update BEFORE UPDATE OF current_owner_user_id ON individuals
FOR EACH ROW EXECUTE FUNCTION ygc_guard_dispute_individual();
CREATE TRIGGER dispute_individual_delete BEFORE DELETE ON individuals
FOR EACH ROW EXECUTE FUNCTION ygc_guard_dispute_individual();
