-- Initial PostgreSQL 18 schema: operations. Generated from disposable metadata.
CREATE TABLE "auto_crawl" (
  id BIGINT PRIMARY KEY CHECK(id=1),
  enabled BIGINT NOT NULL,
  category TEXT NOT NULL,
  year_min BIGINT NOT NULL,
  year_max BIGINT NOT NULL,
  interval_seconds BIGINT NOT NULL,
  next_run DOUBLE PRECISION NOT NULL
);

CREATE TABLE "backup_schedules" (
  target TEXT PRIMARY KEY,
  enabled BIGINT NOT NULL,
  interval_hours BIGINT NOT NULL,
  generations BIGINT NOT NULL,
  next_run DOUBLE PRECISION NOT NULL,
  last_at TEXT,
  last_status TEXT,
  last_error TEXT
);

CREATE TABLE "backup_settings" (
  id BIGINT PRIMARY KEY CHECK(id=1),
  generations BIGINT NOT NULL
);

CREATE TABLE "events" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TEXT NOT NULL,
  mode TEXT NOT NULL,
  reason TEXT NOT NULL
);

CREATE TABLE "paused_review_answers" (
  revision TEXT NOT NULL,
  kind TEXT NOT NULL,
  received_at TEXT NOT NULL,
  payload TEXT NOT NULL,
  PRIMARY KEY(revision,kind)
);

CREATE TABLE "review_settings" (
  id BIGINT PRIMARY KEY CHECK(id=1),
  enabled BIGINT NOT NULL
);

CREATE TABLE "settings" (
  id BIGINT PRIMARY KEY CHECK(id=1),
  mode TEXT NOT NULL,
  message TEXT NOT NULL,
  version BIGINT NOT NULL
);

-- Initial staging state is closed; jobs and review reflection start disabled.
INSERT INTO settings VALUES (1, 'offline', 'Service setup is in progress.', 0);
INSERT INTO auto_crawl VALUES (1, 0, 'electric_acoustic', 1950, 1980, 3600, 0);
INSERT INTO review_settings VALUES (1, 0);
INSERT INTO backup_settings VALUES (1, 10);
INSERT INTO backup_schedules(target,enabled,interval_hours,generations,next_run)
SELECT target,0,24,10,0 FROM (VALUES ('chronicle'),('accounts'),('operations'),('authentication')) AS targets(target);
