"""Generate the initial PostgreSQL DDL from fresh, isolated SQLite metadata.

No existing data, credentials, or account records are read. This is a development
build tool, not a runtime SQL translator. Commit and review generated artifacts.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import sqlite3
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'app/src/ygc/db/postgres'


def quote(name):
    return '"' + name.replace('"', '""') + '"'


def entries(body):
    result, start, depth, quoted = [], 0, 0, None
    i = 0
    while i < len(body):
        c = body[i]
        if quoted:
            if c == quoted:
                if i + 1 < len(body) and body[i + 1] == quoted:
                    i += 1
                else:
                    quoted = None
        elif c in "'\"":
            quoted = c
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
        elif c == ',' and depth == 0:
            result.append(body[start:i].strip())
            start = i + 1
        i += 1
    result.append(body[start:].strip())
    return result


def ddl(path, target):
    with sqlite3.connect(path) as con:
        tables = con.execute("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
        statements, foreign, metadata = [], [], {}
        for table, source in tables:
            columns = con.execute('PRAGMA table_info(' + quote(table) + ')').fetchall()
            metadata[table] = [c[1] for c in columns]
            body = source[source.index('(') + 1:source.rindex(')')]
            parts = []
            for part in entries(body):
                # FK constraints are installed after all tables and unique indexes.
                if re.match(r'FOREIGN\s+KEY', part, re.I):
                    continue
                part = re.sub(r'\s+REFERENCES\s+\w+\s*\([^)]*\)(?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|RESTRICT|SET NULL|NO ACTION|SET DEFAULT))*', '', part, flags=re.I)
                if table not in ('settings', 'auto_crawl', 'review_settings', 'backup_settings'):
                    part = re.sub(r'^("?(?:id|seq)"?)\s+INTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?', r'\1 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', part, flags=re.I)
                part = re.sub(r'\bAUTOINCREMENT\b', '', part, flags=re.I)
                part = re.sub(r'\bINTEGER\b', 'BIGINT', part, flags=re.I)
                part = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', part, flags=re.I)
                part = re.sub(r'\bBLOB\b', 'BYTEA', part, flags=re.I)
                part = re.sub(r'json_valid\((\w+)\)', r"pg_input_is_valid(\1, 'json')", part)
                parts.append(part)
            statements.append('CREATE TABLE ' + quote(table) + ' (\n  ' + ',\n  '.join(parts) + '\n);')
            grouped = {}
            for fk in con.execute('PRAGMA foreign_key_list(' + quote(table) + ')'):
                grouped.setdefault(fk[0], []).append(fk)
            for key, rows in grouped.items():
                rows.sort(key=lambda r: r[1])
                foreign.append('ALTER TABLE ' + quote(table) + ' ADD CONSTRAINT ' + quote('fk_' + table + '_' + str(key)) +
                    ' FOREIGN KEY (' + ','.join(quote(r[3]) for r in rows) + ') REFERENCES ' + quote(rows[0][2]) +
                    ' (' + ','.join(quote(r[4]) for r in rows) + ') ON UPDATE ' + rows[0][5] + ' ON DELETE ' + rows[0][6] + ';')
        indexes = [r[0] + ';' for r in con.execute("SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name")]
    content = '-- Initial PostgreSQL 18 schema: ' + target + '. Generated from disposable metadata.\n' + '\n\n'.join(statements + indexes + foreign) + '\n'
    return content, metadata


def build():
    with tempfile.TemporaryDirectory(prefix='ygc-schema-build-') as tmp:
        root = Path(tmp)
        for key in list(os.environ):
            if key.startswith('YGC_') or key in ('REVERB_API_TOKEN', 'K_SERVICE', 'CLOUD_RUN_JOB'):
                del os.environ[key]
        os.environ.update(YGC_DATA_DIR=tmp, YGC_DB_PATH=str(root/'chronicle.db'), YGC_ACCOUNTS_DB_PATH=str(root/'accounts.sqlite'), YGC_IDENTITY_BACKEND='local_dummy')
        sys.path.insert(0, str(ROOT / 'app/src'))
        from ygc.db.repository import Repository
        from ygc import operations, crawl_backups, direct_queue
        Repository(root/'chronicle.db', root/'accounts.sqlite').init_db()
        operations.auto_crawl()
        operations.chatgpt_review(False)
        operations.retain_paused_answer('schema-fixture', 'fixture', {})
        crawl_backups.policies()
        with direct_queue.transaction():
            pass
        artifacts, manifest = {}, {}
        for target, path in [('chronicle',root/'chronicle.db'), ('accounts',root/'accounts.sqlite'), ('operations',root/'operations.sqlite'), ('authentication',root/'direct-review/queue.sqlite3')]:
            content, tables = ddl(path, target)
            extra = DEST / (target + '_guards.sql')
            if extra.exists():
                content += '\n' + extra.read_text()
            artifacts[target + '_001.sql'] = content
            manifest[target] = {'sha256': hashlib.sha256(content.encode()).hexdigest(), 'tables': tables}
        artifacts['manifest.json'] = json.dumps(manifest, indent=2, ensure_ascii=False) + '\n'
        return artifacts


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    artifacts = build()
    if args.check:
        stale = [name for name, text in artifacts.items() if not (DEST/name).exists() or (DEST/name).read_text() != text]
        if stale:
            raise SystemExit('PostgreSQL artifacts need regeneration: ' + ', '.join(stale))
        print('PostgreSQL schema artifacts agree with isolated SQLite metadata.')
    else:
        for name, text in artifacts.items():
            (DEST/name).write_text(text)
        print('Generated schemas for four stores; no existing data read.')
