const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const assets=path.join(__dirname,'../src/ygc/static');
const account=(id='1',verified=true,status='active')=>({user:{id:Number(id),app_user_id:'uuid-'+id,display_name:'Member '+id,role:'member',status},identity:{email_verified:verified}});
const guitar=(id='12',extra={})=>({id,manufacturer:'Maker',model:'Model',finish:null,year:'1965',serial_number:'SERIAL-'+id,...extra});
const user=id=>({id,display_name:'Member '+id,account_type:'user'});
const transfer=(extra={})=>({id:'23',individual_id:'12',individual:guitar(),viewer_user_id:'1',ownership_kind:'transfer',from_user:user('1'),to_user:user('2'),state:'pending',status:'active',verification_status:'unverified',revision:'a'.repeat(64),created_at:'2026-01-02T03:04:05Z',resolved_at:null,occurred_at:null,acceptance:null,can_write:true,can_accept:false,can_decline:false,can_cancel:true,...extra});
const released=(extra={})=>({id:'24',individual_id:'12',ownership_kind:'release',status:'active',verification_status:'positive',occurred_at:'2026-01-01',body:'Released',...extra});
const view=(extra={})=>({viewer_user_id:'1',individual:guitar(),current_owner_user_id:'1',is_current_owner:true,revision:'a'.repeat(64),can_write:true,can_transfer:true,can_release:true,items:[],next_after:null,...extra});
const accepted=(extra={})=>transfer({state:'accepted',verification_status:'positive',resolved_at:'2026-01-02T04:00:00Z',occurred_at:'2026-01-02T04:00:00Z',acceptance:{accepted_by_user_id:'2',accepted_at:'2026-01-02T04:00:00Z',current_owner_user_id:'1'},can_accept:false,can_decline:false,can_cancel:false,...extra});
const denied=(status=403,code='account_inactive')=>({httpStatus:status,code});
const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}};
function environment({initial=account(),fullPage=false,search=''}={}){
 const ids=new Map(),listeners={};
 class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.dataset={};this.style={};this.value='';this.hidden=false;this.open=false;this.disabled=false;this._text='';this.classList={add(){},remove(){}};this.isConnected=true;this.tabIndex=0}
  set id(value){this._id=value;ids.set(value,this)}get id(){return this._id}
  set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(n=>n.textContent).join('')}
  set innerHTML(value){throw Error('Ownership must be text-only')}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this._text='';this.children=nodes}
  setAttribute(key,value){this[key]=value}removeAttribute(key){delete this[key]}hasAttribute(key){return key in this}
  addEventListener(key,fn){(this.listeners[key]??=[]).push(fn)}dispatchEvent(event){for(const fn of this.listeners[event.type]||[])fn(event)}
  all(){return this.children.flatMap(n=>[n,...n.all()])}contains(n){return n===this||this.all().includes(n)}
  querySelectorAll(selector){return this.all().filter(n=>selector.split(',').map(t=>t.toUpperCase()).includes(n.tagName))}querySelector(s){return this.querySelectorAll(s)[0]||null}
  reset(){for(const n of this.all())n.value=''}focus(){document.activeElement=this}closest(){return null}getClientRects(){return this.hidden?[]:[this.getBoundingClientRect()]}
  getBoundingClientRect(){return {left:20,right:600,top:20,bottom:600}}showModal(){this.open=true;this.opens=(this.opens||0)+1}close(){this.open=false}
 }
 const document={body:new Element('body'),documentElement:{lang:'en'},createElement:tag=>new Element(tag),getElementById:id=>ids.get(id),addEventListener(key,fn){(listeners[key]??=[]).push(fn)}};
 for(const match of fs.readFileSync(path.join(assets,'cloud_account_html.html'),'utf8').matchAll(/<(\w+)[^>]*\bid="([^"]+)"/g)){const n=new Element(match[1]);n.id=match[2];document.body.append(n)}
 let state=initial,busy=false,component,args,updates=0,defaultView=view(),defaultRows=[],defaultTransfer=transfer();const calls=[],replies=[],authCalls=[];
 async function response(value){const data=await value;if(data instanceof Error)throw data;return data?.httpStatus?{ok:false,status:data.httpStatus,json:async()=>({detail:{code:data.code}})}:{ok:true,json:async()=>data}}
 const client={signedIn:Boolean(initial),account:initial,documents:async()=>({terms:{version:'t'},privacy:{version:'p'}}),restore:async()=>initial,
  async signIn(){this.signedIn=true;return this.account=account('1',false)},async logout(){this.signedIn=false;this.account=null},async refreshVerification(){return this.account=account()},async requestEmailVerification(options){authCalls.push(options);return {sent:true,account:this.account}},
  async authorizedFetch(url,options={},verified){
   const call={url,options,verified,account:args.state()?.user?.app_user_id};calls.push(call);assert.match(url,/^\/api\/auth\/(ownership-transfers|transfers\/[1-9][0-9]*|guitars\/[1-9][0-9]*\/(ownership|transfer-users|transfers|release))/);
   const index=replies.findIndex(r=>(!r.match||url.includes(r.match))&&(!r.method||r.method===(options.method||'GET')));
   if(index>=0)return response(replies.splice(index,1)[0].value);
   assert.ok(!options.method||options.method==='GET','Every mutation needs an explicit fixture');
   if(url.startsWith('/api/auth/ownership-transfers'))return response({viewer_user_id:'1',can_write:true,items:defaultRows,next_after:null});
   if(url.includes('/transfer-users'))return response({items:[user('2')],next_offset:null});
   if(url.includes('/ownership'))return response({...defaultView,individual:guitar(url.split('/')[4])});
   return response(defaultTransfer);
  }
 };
 const context=vm.createContext({document,URL,URLSearchParams,Intl,Date,console,location:{search,origin:'https://ygc.example'},CustomEvent:class{constructor(type){this.type=type}},YGCI18n:{t:(key,params={})=>key+(Object.keys(params).length?JSON.stringify(params):'')}});
 context.window=context;context.addEventListener=(key,fn)=>(listeners[key]??=[]).push(fn);
 vm.runInContext(fs.readFileSync(path.join(assets,'overlays.js'),'utf8'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-applications.js'),'utf8').split('export function createApplications')[0].replaceAll('export function','function'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-ownership.js'),'utf8').replace(/^import .*;\n/gm,'').replaceAll('export function','function'),context);
 const create=context.createOwnership;context.createOwnership=value=>{args=value;component=create(value);return component};
 const noOp=()=>({render(){},clear(){},refresh:async()=>{},refreshHistory:async()=>{updates++},failed(){},setCatalogIntent(){}});
 Object.assign(context,{createNotifications:noOp,createIdentityCorrections:noOp,loadCloudAuth:async()=>client,createAvatar:noOp,createProfile:noOp,createGuitars:noOp,createClaims:noOp,createApplications:noOp,readCatalogIntent:()=>null,readClaimIntent:()=>null});
 let ready;if(fullPage)ready=vm.runInContext('(async()=>{'+fs.readFileSync(path.join(assets,'cloud-account-page.js'),'utf8').replace(/^import .*;\n/gm,'')+'})()',context);else{component=context.createOwnership({auth:()=>client,state:()=>state,busy:()=>busy,work:async fn=>{busy=true;component.render();try{return await fn()}finally{busy=false;component.render()}},updated:async()=>{updates++}});ready=Promise.resolve()}
 const control=id=>ids.get(id);
 return {component,context,client,control,calls,authCalls,ready,get updates(){return updates},get dialog(){return control('ownershipDialog')},get inbox(){return control('ownershipInbox')},get history(){return control('ownershipHistory')},
  queue(value,match=null,method=null){replies.push({value,match,method})},setView(value){defaultView=value},setRows(value){defaultRows=value},setTransfer(value){defaultTransfer=value},
  start(){control('ownershipStart').onclick()},dismiss(){control('ownershipClose').onclick()},review(){control('ownershipReview').onclick()},confirm(){return control('ownershipConfirm').onclick()},openTransfer(index=0){return this.inbox.children[index].children[1].onclick()},
  async choose(){field(this,'ownershipSearch','Member');await control('ownershipSearchButton').onclick();control('ownershipCandidates').children[0].children[1].onclick()},
  changeAccount(next){state=next;client.signedIn=Boolean(next);component.render()},navigate(query){context.location.search=query;for(const fn of listeners.popstate||[])fn({})},
  async flush(){for(let i=0;i<12;i++)await new Promise(resolve=>setImmediate(resolve))}
 };
}
const field=(e,id,value)=>{e.control(id).value=value;e.control(id).oninput?.()};
const writes=e=>e.calls.filter(c=>c.options.method==='POST');
async function compose(e,kind='transfer'){await e.component.setCatalogIntent('12');e.start();e.control('ownershipKind').value=kind;e.control('ownershipKind').onchange();if(kind==='transfer')await e.choose();else{field(e,'ownershipDate','2026-01-01');field(e,'ownershipBody','My release')}e.review()}

test('Ownership intent preserves exact BIGINT IDs and rejects duplicate or malformed intent',()=>{const e=environment();for(const id of ['1','9007199254740993','9223372036854775807'])assert.equal(e.context.readOwnershipIntent('?ownership='+id+'&next=https://evil.invalid'),id);for(const value of ['','0','01','-1','9223372036854775808','12\n'])assert.equal(e.context.readOwnershipIntent('?ownership='+encodeURIComponent(value)),'');assert.equal(e.context.readOwnershipIntent('?ownership=12&ownership=12'),'');assert.equal(e.context.readOwnershipIntent('?claim=12'),null)});

for(const initial of [null,account('1',false),account('1',true,'banned')])test('Guest, unverified and banned sessions cannot read private ownership or mutate',async()=>{const e=environment({initial});await e.component.setCatalogIntent('12');await e.component.refresh();e.start();e.review();e.confirm();assert.equal(e.calls.length,0);assert.equal(e.dialog.open,false)});

test('Canonical viewer ID is distinct from UUID app identity, with text-only participant rendering',async()=>{const e=environment();e.setRows([transfer({from_user:{...user('1'),display_name:'<img onerror=x>'}})]);e.setTransfer(transfer({from_user:{...user('1'),display_name:'<img onerror=x>'}}));await e.component.refresh();await e.openTransfer();assert.equal(e.dialog.open,true);assert.match(e.control('ownershipSaved').textContent,/<img/);assert.equal(e.control('ownershipSaved').children.length,0);assert.equal(e.control('ownershipCancel').hidden,false);assert.equal(e.control('ownershipAccept').hidden,true);assert.equal(writes(e).length,0)});

test('Transfer requires a searched explicit candidate, two clicks, exact revision, and no date or extra fields',async()=>{const e=environment();await e.component.setCatalogIntent('12');e.start();field(e,'ownershipSearch','Member');e.review();e.confirm();assert.equal(writes(e).length,0);await e.choose();e.review();assert.equal(writes(e).length,0);e.queue({transfer:transfer()},'/transfers','POST');e.confirm();e.confirm();await e.flush();assert.equal(writes(e).length,1);const call=writes(e)[0];assert.equal(call.url,'/api/auth/guitars/12/transfers');assert.equal(call.verified,true);assert.equal(call.options.cache,'no-store');assert.deepEqual(JSON.parse(call.options.body),{to_user_id:'2',revision:'a'.repeat(64)});assert.equal(e.control('ownershipCancel').hidden,false);assert.equal(e.updates,1)});

test('Changing search or action invalidates the explicit candidate and confirmation',async()=>{const e=environment();await compose(e);field(e,'ownershipSearch','Other');e.confirm();assert.equal(writes(e).length,0);assert.equal(e.control('ownershipConfirm').hidden,true);assert.equal(e.control('ownershipReview').disabled,true);await e.choose();e.review();e.control('ownershipKind').value='release';e.control('ownershipKind').onchange();e.confirm();assert.equal(writes(e).length,0)});

test('Blank recipient search never enumerates users; pagination is bounded and explicit',async()=>{const e=environment();await e.component.setCatalogIntent('12');e.start();await e.control('ownershipSearchButton').onclick();assert.equal(e.calls.filter(c=>c.url.includes('/transfer-users')).length,0);field(e,'ownershipSearch','2');e.queue({items:[user('2')],next_offset:20},'/transfer-users');await e.control('ownershipSearchButton').onclick();assert.equal(e.control('ownershipSearchMore').hidden,false);await e.control('ownershipSearchMore').onclick();assert.match(e.calls.at(-1).url,/q=2&offset=20&limit=20$/);assert.ok(e.calls.every(c=>!c.url.includes('viewer_id')))});

for(const extra of [{can_write:false},{can_write:null},{can_write:'true'},{can_transfer:false},{is_current_owner:false,current_owner_user_id:'2'}])test('Non-writable/non-owner capability cannot prepare Transfer',async()=>{const e=environment();e.setView(view(extra));await e.component.setCatalogIntent('12');e.start();e.review();e.confirm();assert.equal(writes(e).length,0)});

test('Release records selected date/body only and displays actual refreshed owner after historical evaluation',async()=>{const e=environment();await compose(e,'release');e.setView(view({revision:'b'.repeat(64),items:[released()]}));e.queue(view(),'/ownership');e.queue({claim:released(),ownership:view()},'/release','POST');await e.confirm();assert.equal(writes(e).length,1);assert.deepEqual(JSON.parse(writes(e)[0].options.body),{occurred_at:'2026-01-01',body:'My release',revision:'a'.repeat(64)});assert.equal(e.dialog.open,false);assert.match(e.control('ownershipIntentDetail').textContent,/#1/);assert.match(e.history.textContent,/ownership.release/);assert.equal(e.updates,1)});

test('Creation UI offers Transfer/Release only and future Release dates cannot be confirmed',async()=>{const e=environment();await e.component.setCatalogIntent('12');e.start();assert.deepEqual(e.control('ownershipKind').children.map(n=>n.value),['transfer','release']);e.control('ownershipKind').value='release';e.control('ownershipKind').onchange();field(e,'ownershipDate','9999-01-01');e.review();e.confirm();assert.equal(writes(e).length,0);assert.match(e.control('ownershipMessage').textContent,/ownership.invalid/)});

for(const actionName of ['accept','decline'])test('Recipient '+actionName+' is separate from Verification and requires confirmation',async()=>{const e=environment({initial:account('2')});const row=transfer({viewer_user_id:'2',can_accept:true,can_decline:true,can_cancel:false});e.queue({viewer_user_id:'2',items:[row],next_after:null,can_write:true},'ownership-transfers');e.setTransfer(row);await e.component.refresh();await e.openTransfer();e.control('ownership'+actionName[0].toUpperCase()+actionName.slice(1)).onclick();assert.equal(writes(e).length,0);const result=actionName==='accept'?accepted({viewer_user_id:'2'}):transfer({...row,state:'declined',resolved_at:'2026-01-02T04:00:00Z',can_accept:false,can_decline:false});e.queue({transfer:result},'/resolve','POST');e.queue({viewer_user_id:'2',items:[result],next_after:null,can_write:true},'ownership-transfers');await e.confirm();assert.deepEqual(JSON.parse(writes(e)[0].options.body),{action:actionName,revision:'a'.repeat(64)});assert.ok(!e.calls.some(c=>c.url.includes('owner-responses')));if(actionName==='accept'){assert.match(e.control('ownershipEvidence').textContent,/2026-01-02T04:00:00Z/);assert.match(e.control('ownershipEvidence').textContent,/ownership.independent/)}assert.equal(e.control('ownershipAccept').disabled,true)});

test('Accepted Negative Transfer retains acceptance evidence and exposes no agreement actions',async()=>{const e=environment();e.setRows([accepted({verification_status:'negative'})]);e.setTransfer(accepted({verification_status:'negative'}));await e.component.refresh();await e.openTransfer();assert.match(e.control('ownershipSaved').textContent,/ownership.accepted/);assert.match(e.control('ownershipSaved').textContent,/chronicle.negative/);assert.match(e.control('ownershipEvidence').textContent,/ownership.accepted_by: #2/);for(const id of ['ownershipAccept','ownershipDecline','ownershipCancel'])assert.equal(e.control(id).hidden,true);assert.equal(writes(e).length,0)});

for(const interruption of ['close','new intent','back','signout','other account','unverified','ban'])test('Delayed preflight after '+interruption+' never writes or reopens',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/ownership');const job=e.confirm();if(interruption==='close')e.dismiss();else if(interruption==='new intent')await e.component.setCatalogIntent('13');else if(interruption==='back'){e.navigate('');await e.component.setCatalogIntent(null)}else e.changeAccount(interruption==='signout'?null:account(interruption==='other account'?'2':'1',interruption!=='unverified',interruption==='ban'?'banned':'active'));held.resolve(view());await job;assert.equal(writes(e).length,0);assert.equal(e.dialog.open,false)});

for(const interruption of ['close','new intent','back'])test('Completed mutation after '+interruption+' refreshes account history without reviving dialog',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/transfers','POST');const job=e.confirm();await e.flush();assert.equal(writes(e).length,1);if(interruption==='close')e.dismiss();else if(interruption==='new intent')await e.component.setCatalogIntent('13');else{e.navigate('');await e.component.setCatalogIntent(null)}held.resolve({transfer:transfer()});await job;assert.equal(e.dialog.open,false);assert.equal(e.updates,1);if(interruption==='new intent')assert.match(e.control('ownershipIntentDetail').textContent,/SERIAL-13/)});

for(const interruption of ['signout','other account'])test('Completed mutation after '+interruption+' never refreshes/exposes another session',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/transfers','POST');const job=e.confirm();await e.flush();e.changeAccount(interruption==='signout'?null:account('2'));held.resolve({transfer:transfer()});await job;assert.equal(e.dialog.open,false);assert.equal(e.updates,0);assert.equal(e.inbox.children.length,0)});

test('Stale ownership revision requires reviewing again and never silently rebases a confirmation',async()=>{const e=environment();await compose(e);e.queue(view({revision:'b'.repeat(64)}),'/ownership');await e.confirm();assert.equal(writes(e).length,0);assert.match(e.control('ownershipMessage').textContent,/ownership.conflict/);assert.equal(e.control('ownershipConfirm').hidden,true);e.review();e.queue(view({revision:'b'.repeat(64)}),'/ownership');e.queue({transfer:transfer()},'/transfers','POST');await e.confirm();assert.equal(JSON.parse(writes(e)[0].options.body).revision,'b'.repeat(64))});

test('Read-only preflight retains private review but prevents POST',async()=>{const e=environment();await compose(e);e.queue(view({can_write:false}),'/ownership');await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.dialog.open,true);assert.equal(e.control('ownershipReview').disabled,true);assert.match(e.control('ownershipMessage').textContent,/applications.read_only/)});

for(const code of [403,503])test('Service restriction '+code+' at mutation freshly revalidates private read access',async()=>{const e=environment();await compose(e);e.queue(view(),'/ownership');e.queue(denied(code,'service_restricted'),'/transfers','POST');e.queue(view({can_write:false}),'/ownership');await e.confirm();assert.equal(writes(e).length,1);assert.equal(e.dialog.open,true);assert.equal(e.control('ownershipReview').disabled,true);assert.match(e.control('ownershipMessage').textContent,/applications.service_restricted/)});

for(const code of [401,403,404])test('Access denial '+code+' purges private participant details',async()=>{const e=environment();e.setRows([transfer()]);await e.component.refresh();await e.openTransfer();e.queue(denied(code),'ownership-transfers');await e.component.refresh();assert.equal(e.dialog.open,false);assert.equal(e.inbox.children.length,0);assert.equal(e.control('ownershipSaved').textContent,'');assert.ok(e.calls.every(c=>c.verified===true))});

for(const result of [Error('response lost'),denied(500,'temporary_failure'),{transfer:{}}])test('Unknown result survives dismissal and requires successful check plus explicit acknowledgment',async()=>{const e=environment();await compose(e);e.queue(result,'/transfers','POST');await e.confirm();assert.equal(writes(e).length,1);assert.equal(e.control('ownershipReview').disabled,true);e.dismiss();e.start();assert.equal(e.control('ownershipReview').disabled,true);assert.equal(e.control('ownershipCheck').hidden,false);assert.equal(e.control('ownershipAcknowledge').hidden,true);e.setView(view({revision:'b'.repeat(64),items:[transfer()]}));await e.control('ownershipCheck').onclick();assert.match(e.control('ownershipSaved').textContent,/#23/);assert.equal(e.control('ownershipAcknowledge').hidden,false);assert.equal(writes(e).length,1);e.control('ownershipAcknowledge').onclick();assert.equal(e.control('ownershipCheck').hidden,true);assert.equal(e.control('ownershipConfirm').hidden,true);assert.equal(writes(e).length,1)});

test('Unknown committed Release can be recovered from Formerly Owned after ownership becomes Unknown',async()=>{const e=environment();await compose(e,'release');e.queue(view(),'/ownership');e.queue(Error('response lost'),'/release','POST');e.setView(view({is_current_owner:false,current_owner_user_id:null,can_transfer:false,can_release:false,revision:'b'.repeat(64),items:[released()]}));await e.confirm();e.dismiss();assert.equal(e.control('ownershipStart').disabled,false);e.start();assert.equal(e.dialog.open,true);assert.equal(e.control('ownershipReview').disabled,true);await e.control('ownershipCheck').onclick();assert.match(e.control('ownershipSaved').textContent,/ownership.release/);e.control('ownershipAcknowledge').onclick();e.dismiss();assert.equal(e.control('ownershipStart').disabled,true);assert.equal(writes(e).length,1)});

test('Preflight transport failure stays retryable without unknown-write warning',async()=>{const e=environment();await compose(e);e.queue(Error('offline'),'/ownership');await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.control('ownershipCheck').hidden,true);assert.equal(e.control('ownershipReview').disabled,false)});

test('A failed uncertain-result check cannot unlock another submission',async()=>{const e=environment();await compose(e);e.queue(Error('response lost'),'/transfers','POST');await e.confirm();e.queue(Error('offline'),'/ownership');await e.control('ownershipCheck').onclick();e.control('ownershipAcknowledge').onclick();assert.equal(e.control('ownershipAcknowledge').hidden,true);assert.equal(e.control('ownershipReview').disabled,true);assert.equal(writes(e).length,1)});

test('Late recipient search after edits or close cannot restore candidate choice',async()=>{const e=environment(),held=deferred();await e.component.setCatalogIntent('12');e.start();field(e,'ownershipSearch','Old');e.queue(held.promise,'/transfer-users');const job=e.control('ownershipSearchButton').onclick();field(e,'ownershipSearch','New');held.resolve({items:[user('2')],next_offset:null});await job;assert.equal(e.control('ownershipCandidates').children.length,0);assert.equal(e.control('ownershipReview').disabled,true)});

test('Late openGuitar read after navigation never opens the newer selection',async()=>{const e=environment(),held=deferred();e.queue(held.promise,'/12/ownership');const job=e.component.openGuitar('12');await e.component.setCatalogIntent('13');held.resolve(view());await job;assert.equal(e.dialog.open,false);assert.match(e.control('ownershipIntentDetail').textContent,/SERIAL-13/)});

for(const malformed of [view({viewer_user_id:'uuid-1'}),view({revision:'old'}),view({items:[transfer({from_user:user('3'),to_user:user('4')})]}),view({items:[transfer({state:'accepted',acceptance:null})]}),view({items:[released({individual_id:'13'})]})])test('Malformed private ownership response cannot enable changes',async()=>{const e=environment();e.queue(malformed,'/ownership');await e.component.setCatalogIntent('12');e.start();e.review();e.confirm();assert.equal(e.dialog.open,false);assert.equal(writes(e).length,0)});

test('Large viewer, recipient, Claim and guitar IDs stay exact throughout private API requests',async()=>{const id='9007199254740993',e=environment();e.setView(view({viewer_user_id:id,current_owner_user_id:id}));await e.component.setCatalogIntent('9223372036854775807');e.start();field(e,'ownershipSearch','Large');e.queue({items:[user('9007199254740994')],next_offset:null},'/transfer-users');await e.control('ownershipSearchButton').onclick();e.control('ownershipCandidates').children[0].children[1].onclick();e.review();e.queue({transfer:transfer({id:'9007199254740995',individual_id:'9223372036854775807',individual:guitar('9223372036854775807'),viewer_user_id:id,from_user:user(id),to_user:user('9007199254740994')})},'/transfers','POST');await e.confirm();assert.equal(JSON.parse(writes(e)[0].options.body).to_user_id,'9007199254740994');assert.match(writes(e)[0].url,/9223372036854775807/)});

test('Account login/verification and Back/Forward preserve ownership intent without automatic mutation',async()=>{const e=environment({initial:null,fullPage:true,search:'?ownership=12'});await e.ready;await e.flush();assert.match(e.control('ownershipIntentStatus').textContent,/catalog.acquire_sign_in/);await e.control('cloudAccountForm').onsubmit({preventDefault(){}});await e.flush();assert.match(e.control('ownershipIntentStatus').textContent,/catalog.acquire_verify/);await e.control('refreshVerification').onclick();await e.flush();assert.match(e.control('ownershipIntentStatus').textContent,/ownership.ready/);e.start();field(e,'ownershipBody','PRIVATE');e.navigate('?ownership=13');await e.flush();assert.equal(e.dialog.open,false);assert.equal(e.control('ownershipBody').value,'');assert.match(e.control('ownershipIntentDetail').textContent,/SERIAL-13/);e.navigate('?ownership=12&ownership=13');await e.flush();assert.match(e.control('ownershipIntentStatus').textContent,/catalog.acquire_invalid/);assert.equal(writes(e).length,0)});


test('An unknown mutation followed by a failed ownership read cannot open an unverified recovery dialog',async()=>{const e=environment();await compose(e);e.queue(Error('response lost'),'/transfers','POST');await e.confirm();e.dismiss();e.queue(Error('offline'),'/ownership');await assert.doesNotReject(e.component.openGuitar('12'));assert.equal(e.dialog.open,false);assert.equal(e.control('ownershipStart').disabled,true);await e.component.openGuitar('12');assert.equal(e.dialog.open,true);assert.equal(e.control('ownershipCheck').hidden,false)});

test('Deleted historical participants keep their recorded IDs while remaining unavailable destinations',async()=>{const e=environment(),row=accepted({to_user:{id:'2',display_name:null,account_type:null}});e.setRows([row]);e.setTransfer(row);await e.component.refresh();await e.openTransfer();assert.match(e.control('ownershipSaved').textContent,/ownership.unavailable_user \(#2\)/);assert.match(e.control('ownershipEvidence').textContent,/#2/);assert.equal(e.control('ownershipAccept').hidden,true);e.dismiss();await e.component.setCatalogIntent('12');e.start();field(e,'ownershipSearch','2');e.queue({items:[{id:'2',display_name:null,account_type:null}],next_offset:null},'/transfer-users');await e.control('ownershipSearchButton').onclick();assert.equal(e.control('ownershipCandidates').children.length,0);assert.equal(writes(e).length,0)});


test('A late failed restriction recheck cannot purge a newer authorized guitar view',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(view(),'/12/ownership');e.queue(denied(403,'service_restricted'),'/transfers','POST');e.queue(held.promise,'/12/ownership');const job=e.confirm();await e.flush();await e.component.setCatalogIntent('13');assert.match(e.control('ownershipIntentDetail').textContent,/SERIAL-13/);held.resolve(Error('offline'));await job;assert.match(e.control('ownershipIntentDetail').textContent,/SERIAL-13/);assert.equal(e.dialog.open,false)});


test('An older inbox denial cannot clear a newer authorized ownership selection',async()=>{const e=environment(),held=deferred();await e.component.setCatalogIntent('12');e.queue(held.promise,'ownership-transfers');const job=e.component.refresh();await e.component.setCatalogIntent('13');held.resolve(denied(403));await job;assert.match(e.control('ownershipIntentDetail').textContent,/SERIAL-13/);assert.equal(e.control('ownershipStart').disabled,false)});

test('Private inbox and history cursors stay exact and a newer read supersedes an old response',async()=>{const e=environment(),held=deferred();e.queue({viewer_user_id:'1',can_write:true,items:[transfer({id:'9007199254740995'})],next_after:'9007199254740995'},'ownership-transfers');await e.component.refresh();e.queue({viewer_user_id:'1',can_write:true,items:[transfer({id:'9007199254740994'})],next_after:null},'ownership-transfers');await e.control('ownershipInboxMore').onclick();assert.match(e.calls.at(-1).url,/after=9007199254740995$/);assert.match(e.inbox.textContent,/#9007199254740994/);e.queue(held.promise,'ownership-transfers');const job=e.component.refresh();e.setRows([transfer({id:'40'})]);await e.component.refresh();held.resolve({viewer_user_id:'1',can_write:true,items:[transfer({id:'10'})],next_after:null});await job;assert.match(e.inbox.textContent,/#40/);assert.doesNotMatch(e.inbox.textContent,/#10/);e.queue(view({items:[released({id:'9007199254740995'})],next_after:'9007199254740995'}),'/ownership');await e.component.setCatalogIntent('12');await e.control('ownershipHistoryMore').onclick();assert.match(e.calls.at(-1).url,/after=9007199254740995$/);assert.equal(writes(e).length,0)});


test('An unknown result after dismissal stays visible in the inbox until checked and acknowledged',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/transfers','POST');const job=e.confirm();await e.flush();e.dismiss();await e.component.setCatalogIntent(null);held.resolve(Error('response lost'));await job;assert.match(e.control('ownershipInboxStatus').textContent,/ownership.uncertain/);await e.component.refresh();assert.match(e.control('ownershipInboxStatus').textContent,/ownership.uncertain/);await e.component.openGuitar('12');await e.control('ownershipCheck').onclick();e.control('ownershipAcknowledge').onclick();assert.doesNotMatch(e.control('ownershipInboxStatus').textContent,/ownership.uncertain/);assert.equal(writes(e).length,1)});
