const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const assets=path.join(__dirname,'../src/ygc/static');
const account=(id='2',verified=true,status='active',role='member')=>({user:{id,app_user_id:'uuid-'+id,display_name:'Member '+id,role,status},identity:{email_verified:verified}});
const now='2026-10-07T01:00:00Z',revision='a'.repeat(64);
const person=(id='1')=>({id,display_name:'Person '+id,account_type:'user'});
const guitar=()=>({id:'12',manufacturer:'Maker',model:'Model',finish:'Natural',year:'1965',serial_number:'S1'});
const option=(extra={})=>({claim_id:'41',individual:guitar(),applicant:person('2'),owner:person('1'),requested_at:now,verification_status:'negative',decline:{reason:'Owner decline reason',created_at:now,acknowledged_at:null},eligible:true,can_acknowledge:true,can_appeal:true,wait_until:now,wait_days:14,revision,can_write:true,case_id:null,...extra});
const caseRow=(extra={})=>({id:'31',individual_id:'12',owner_id:'1',locked_owner_id:'1',winner_id:null,status:'open',version:'9007199254740993',created_at:now,updated_at:now,decision:null,reason:null,individual:guitar(),owner:person(),current_owner:person(),applicants:[person('2')],round_number:'1',round_phase:'collecting',...extra});
const evidence=(extra={})=>({id:'51',claim_id:'41',author_id:'2',author_name:'Person 2',created_at:now,published_summary:null,published_at:null,round_number:'1',can_publish:false,explanation:'My private explanation',summary:'Summary for review',filename:'evidence.pdf',content_type:'application/pdf',has_attachment:true,...extra});
const detail=({admin=false,viewer=admin?'9':'2',submitted=false,...extra}={})=>{
 const round={id:'61',number:'1',phase:'collecting',request_reason:'',created_at:now,parties:[{claim_id:'41',user_id:'1',display_name:'Person 1',submitted_at:null,can_submit:!admin&&viewer==='1'},{claim_id:'41',user_id:'2',display_name:'Person 2',submitted_at:submitted?now:null,can_submit:!admin&&viewer==='2'&&!submitted}]};
 return {...caseRow(),viewer_user_id:viewer,can_write:true,is_admin:admin,can_reopen:false,claims:[{claim_id:'41',applicant_id:'2',applicant_name:'Person 2',decline_reason:'Owner decline reason',requested_at:now}],round,rounds:[round],evidence:submitted?[evidence({can_publish:admin})]:[],events:[],...extra};
};
const denied=(status=403,code='account_inactive',raw='SECRET backend stack')=>({httpStatus:status,code,raw});
const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}};
function environment({admin=false,initial=account(admin?'9':'2',true,'active',admin?'admin':'member'),storage=new Map(),storageDenied=false}={}){
 const ids=new Map(),listeners={};
 class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.dataset={};this.style={};this.value='';this.files=[];this.hidden=false;this.open=false;this.disabled=false;this._text='';this.classList={add(){},remove(){}};this.isConnected=true;this.tabIndex=0}
  set id(value){this._id=value;ids.set(value,this)}get id(){return this._id}
  set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(n=>n.textContent).join('')}
  set innerHTML(value){throw Error('Ownership must be text-only')}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this._text='';this.children=nodes}
  setAttribute(key,value){this[key]=value}removeAttribute(key){delete this[key]}hasAttribute(key){return key in this}
  addEventListener(key,fn){(this.listeners[key]??=[]).push(fn)}dispatchEvent(event){for(const fn of this.listeners[event.type]||[])fn(event)}
  all(){return this.children.flatMap(n=>[n,...n.all()])}contains(n){return n===this||this.all().includes(n)}
  querySelectorAll(selector){return this.all().filter(n=>selector.split(',').map(t=>t.toUpperCase()).includes(n.tagName))}querySelector(s){return this.querySelectorAll(s)[0]||null}
  click(){this.onclick?.()}remove(){}reset(){for(const n of this.all())n.value=''}focus(){document.activeElement=this}closest(){return null}getClientRects(){return this.hidden?[]:[this.getBoundingClientRect()]}
  getBoundingClientRect(){return {left:20,right:600,top:20,bottom:600}}showModal(){this.open=true;this.opens=(this.opens||0)+1}close(){this.open=false}
 }
 const document={body:new Element('body'),documentElement:{lang:'en'},createElement:tag=>new Element(tag),getElementById:id=>ids.get(id),addEventListener(key,fn){(listeners[key]??=[]).push(fn)}};
 for(const match of fs.readFileSync(path.join(assets,'cloud_account_html.html'),'utf8').matchAll(/<(\w+)[^>]*\bid="([^"]+)"/g)){const n=new Element(match[1]);n.id=match[2];document.body.append(n)}
 let state=initial,busy=false,component,args,updates=0,defaultDetail=detail({admin}),defaultOption=option(),defaultCases=[],defaultOptions=[option()];const calls=[],replies=[],denials=[],created=[],revoked=[];
 async function response(value){const data=await value;if(data instanceof Error)throw data;if(data instanceof Blob)return {ok:true,headers:{get:()=>data.type},blob:async()=>data};return data?.httpStatus?{ok:false,status:data.httpStatus,json:async()=>({detail:{code:data.code,message:data.raw,individual_id:'987654321'}})}:{ok:true,json:async()=>data}}
 const client={signedIn:Boolean(initial),account:initial,documents:async()=>({terms:{version:'t'},privacy:{version:'p'}}),restore:async()=>initial,
  async signIn(){this.signedIn=true;return this.account=account('1',false)},async logout(){this.signedIn=false;this.account=null},async refreshVerification(){return this.account=account()},
  async authorizedFetch(url,options={},verified){
   calls.push({url,options,verified,account:args.state()?.user?.app_user_id});
   const index=replies.findIndex(r=>(!r.match||url.includes(r.match))&&(!r.method||r.method===(options.method||'GET')));
   if(index>=0)return response(replies.splice(index,1)[0].value);
   assert.ok(!options.method||options.method==='GET','Every mutation needs a fixture');
   if(/\/options\/[0-9]+$/.test(url))return response(defaultOption);
   if(/\/[0-9]+$/.test(url))return response(defaultDetail);
   return response({items:url.includes('/options?')?defaultOptions:defaultCases,next_after:null,can_write:true,viewer_user_id:initial?.user?.id||'2'});
  }
 };
 const sessionStorage={getItem(key){if(storageDenied)throw Error('Denied storage');return storage.get(key)??null},setItem(key,value){if(storageDenied)throw Error('Denied storage');storage.set(key,value)},removeItem(key){if(storageDenied)throw Error('Denied storage');storage.delete(key)}};
 const context=vm.createContext({document,URL:{createObjectURL:blob=>{const url='blob:fixture-'+created.length;created.push({blob,url});return url},revokeObjectURL:url=>revoked.push(url)},URLSearchParams,Intl,Date,console,FormData,Blob,sessionStorage,location:{search:'',origin:'https://ygc.example'},CustomEvent:class{constructor(type){this.type=type}},YGCI18n:{t:(key,params={})=>key+(Object.keys(params).length?JSON.stringify(params):'')}});
 context.window=context;context.addEventListener=(key,fn)=>(listeners[key]??=[]).push(fn);
 vm.runInContext(fs.readFileSync(path.join(assets,'overlays.js'),'utf8'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-applications.js'),'utf8').split('export function createApplications')[0].replaceAll('export function','function'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-disputes.js'),'utf8').replace(/^import .*;\n/gm,'').replaceAll('export function','function'),context);
 const create=context.createDisputes;context.createDisputes=value=>{args=value;component=create(value);return component};
 const root=new Element('section');root.id='disputeBrowser';document.body.append(root);
 component=context.createDisputes({auth:()=>client,state:()=>state,busy:()=>busy,admin,onUnauthorized:error=>denials.push(error),work:async fn=>{busy=true;component.render();try{return await fn()}finally{busy=false;component.render()}},updated:async()=>{updates++}});
 const ready=Promise.resolve();
 const control=id=>ids.get(id);
 return {component,context,client,control,calls,denials,created,revoked,storage,ready,get updates(){return updates},get dialog(){return control('disputeDialog')},get list(){return control('disputeList')},get history(){return control('disputeRounds')},
  queue(value,match=null,method=null){replies.push({value,match,method})},setDetail(value){defaultDetail=value},setOption(value){defaultOption=value},setCases(value){defaultCases=value},setOptions(value){defaultOptions=value},
  open(id='31'){return component.openDispute(id)},openOption(id='41'){return component.openDisputeOption(id)},dismiss(){control('disputeClose').onclick()},review(){return control('disputeForm').onsubmit({preventDefault(){}})},confirm(){return control('disputeConfirm').onclick()},

  changeAccount(next){state=next;client.signedIn=Boolean(next);component.render()},event(type){for(const fn of listeners[type]||[])fn({})},
  async flush(){for(let i=0;i<12;i++)await new Promise(resolve=>setImmediate(resolve))}
 };
}
const field=(e,id,value)=>{e.control(id).value=value;e.control(id).oninput?.();e.control(id).onchange?.()};
const writes=e=>e.calls.filter(c=>c.options.method==='POST');
const file=()=>new Blob(['%PDF fixture'],{type:'application/pdf'});
async function compose(e,{opening=false}={}){if(opening)await e.openOption();else await e.open();field(e,'disputeExplanation','My private explanation');field(e,'disputeSummary','Summary for review');if(opening)e.control('disputeAttachment').files=[file()];await e.review()}
function completed(admin=false){return detail({admin,submitted:true,version:'9007199254740994'})}
for(const initial of [null,account('2',false),account('2',true,'banned'),account('2',true,'disabled')])test('Ineligible account never reads a dispute',async()=>{const e=environment({initial});await e.component.refresh();await e.open();await e.openOption();assert.equal(e.calls.length,0);assert.equal(e.dialog.open,false)});
test('Participant entry uses fresh private reads and exact BIGINT version',async()=>{const e=environment();await e.component.refresh();await e.open();assert.match(e.control('disputeMeta').textContent,/Acquire|acquire/);assert.equal(e.control('disputeForm').hidden,false);assert.equal(e.control('disputeClaim').hidden,true);assert.equal(writes(e).length,0);for(const c of e.calls){assert.equal(c.verified,true);assert.equal(c.options.cache,'no-store');assert.equal(c.options.credentials,'omit');assert.equal(c.options.redirect,'error');assert.doesNotMatch(c.url,/viewer|user_id/)}});
test('Decline acceptance is explicitly reviewed and confirmed separately from notification reads',async()=>{const e=environment();await e.openOption();await e.control('disputeAccept').onclick();assert.equal(writes(e).length,0);assert.match(e.control('disputePreview').textContent,/Owner decline reason/);const accepted=option({can_acknowledge:false,can_appeal:false,revision:'b'.repeat(64),decline:{reason:'Owner decline reason',created_at:now,acknowledged_at:now}});e.queue({option:accepted},'/acknowledge','POST');await e.confirm();assert.equal(writes(e).length,1);assert.deepEqual(JSON.parse(writes(e)[0].options.body),{revision});assert.equal(e.control('disputeAccept').hidden,true);assert.equal(e.control('disputeForm').hidden,true)});
test('Appeal requires explanation, summary and initial attachment',async()=>{for(const missing of ['explanation','summary','file']){const e=environment();await e.openOption();field(e,'disputeExplanation',missing==='explanation'?'':'private');field(e,'disputeSummary',missing==='summary'?'':'summary');if(missing!=='file')e.control('disputeAttachment').files=[file()];await e.review();await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.control('disputeConfirm').hidden,true)}});
test('Confirmed appeal sends multipart exact opening payload and does not double-submit',async()=>{const e=environment();await compose(e,{opening:true});e.queue({detail:completed()},'/evidence','POST');const first=e.confirm();e.confirm();await first;assert.equal(writes(e).length,1);const payload=JSON.parse(writes(e)[0].options.body.get('data'));assert.deepEqual(payload,{revision,case_id:null,version:null,round_number:null,explanation:'My private explanation',summary:'Summary for review'});assert.ok(writes(e)[0].options.body.get('attachment'));assert.equal(e.control('disputeForm').hidden,true);assert.equal(e.storage.size,0)});
test('Existing round submission uses exact decimal-string CAS and no attachment required',async()=>{const e=environment();await compose(e);e.queue({detail:completed()},'/evidence','POST');await e.confirm();assert.equal(writes(e).length,1);const payload=JSON.parse(writes(e)[0].options.body.get('data'));assert.equal(payload.case_id,'31');assert.equal(payload.version,'9007199254740993');assert.equal(payload.round_number,'1');assert.equal(payload.revision,null);assert.equal(e.control('disputeForm').hidden,true);assert.match(e.history.textContent,/Summary for review/)});
test('The submitting party sees its private original while the other sees only reviewed summary',async()=>{const e=environment();e.setDetail(completed());await e.open();assert.match(e.history.textContent,/My private explanation/);assert.equal(e.history.querySelectorAll('button').filter(n=>n.dataset.disputeAttachment).length,1);e.dismiss();const row=evidence();for(const key of ['explanation','summary','filename','content_type','has_attachment'])delete row[key];row.published_summary='Reviewed public summary';row.published_at=now;e.setDetail(detail({viewer:'1',submitted:true,evidence:[row]}));await e.open();assert.match(e.history.textContent,/Reviewed public summary/);assert.doesNotMatch(e.history.textContent,/My private explanation|Summary for review/);assert.equal(e.history.querySelectorAll('button').length,0)});
test('Another participant private evidence appearing in DTO fails closed',async()=>{const e=environment();e.setDetail(detail({viewer:'1',submitted:true}));await e.open();assert.equal(e.history.children.length,0);assert.equal(e.control('disputeForm').hidden,true)});
for(const interruption of ['account','unverified','ban','signout','popstate','pagehide','close'])test('Late detail response after '+interruption+' cannot restore private content',async()=>{const e=environment(),held=deferred();e.queue(held.promise,'/31');const job=e.open();if(interruption==='close')e.dismiss();else if(['popstate','pagehide'].includes(interruption))e.event(interruption);else e.changeAccount(interruption==='signout'?null:account(interruption==='account'?'3':'2',interruption!=='unverified',interruption==='ban'?'banned':'active'));held.resolve(completed());await job;assert.equal(e.history.children.length,0);assert.equal(e.dialog.open,false);assert.equal(writes(e).length,0)});
for(const outcome of [Error('SECRET lost reply'),denied(500),denied(503),{}, {detail:detail({version:1})}])test('Unknown mutation result requires successful fresh read and explicit retry acknowledgement',async()=>{const e=environment();await compose(e);e.queue(outcome,'/evidence','POST');await e.confirm();assert.equal(writes(e).length,1);assert.equal(e.control('disputeReview').disabled,true);assert.equal(e.control('disputeCheck').hidden,false);assert.equal(e.storage.size,1);await e.review();await e.confirm();assert.equal(writes(e).length,1);e.queue(denied(503),'/31');await e.control('disputeCheck').onclick();assert.equal(e.control('disputeAcknowledge').hidden,true);await e.control('disputeCheck').onclick();assert.equal(e.control('disputeAcknowledge').hidden,false);assert.equal(e.control('disputeReview').disabled,true);e.control('disputeAcknowledge').onclick();assert.equal(e.control('disputeReview').disabled,false);assert.equal(e.storage.size,0);assert.equal(writes(e).length,1);assert.doesNotMatch(e.control('disputeMessage').textContent,/SECRET/)});
for(const status of [400,409,422])test('Definitive mutation rejection '+status+' blocks retry until fresh read',async()=>{const e=environment();await compose(e);e.queue(denied(status),'/evidence','POST');await e.confirm();assert.equal(e.control('disputeReview').disabled,true);assert.equal(e.storage.size,0);await e.control('disputeReload').onclick();assert.equal(e.control('disputeReview').disabled,false);assert.equal(writes(e).length,1)});
for(const status of [401,403,404])test('Lost access '+status+' clears all private content',async()=>{const e=environment();await compose(e);e.queue(denied(status),'/evidence','POST');await e.confirm();assert.equal(e.dialog.open,false);assert.equal(e.history.children.length,0);assert.equal(e.control('disputeExplanation').value,'');assert.equal(e.list.children.length,0)});
test('Read-only preserves case evidence with all mutations disabled',async()=>{const e=environment();const d=completed();d.can_write=false;e.setDetail(d);await e.open();assert.match(e.history.textContent,/private explanation/);assert.equal(e.control('disputeReview').disabled,true);assert.equal(writes(e).length,0)});
test('Service restriction on a write retains data only after successful fresh read',async()=>{const e=environment();await compose(e);e.queue(detail(),'/31','GET');e.queue(denied(403,'service_restricted'),'/evidence','POST');const d=detail();d.can_write=false;e.queue(d,'/31','GET');await e.confirm();assert.equal(e.dialog.open,true);assert.equal(e.control('disputeReview').disabled,true);assert.match(e.control('disputeMessage').textContent,/service_restricted/)});
test('Untrusted values use plaintext DOM without links, images or scripts',async()=>{const e=environment(),attack='<img src=x onerror=secret>';const d=completed();d.evidence[0].summary=d.evidence[0].explanation=attack;d.claims[0].applicant_name=attack;e.setDetail(d);await e.open();assert.match(e.history.textContent,/<img/);assert.equal(e.dialog.querySelectorAll('img,script,a').length,0)});
for(const [key,value] of [['id',31],['version',9007199254740993],['version','01'],['round_number','9223372036854775808'],['viewer_user_id','1e3'],['private_token','SECRET']])test('Malformed detail field '+key+' fails closed',async()=>{const e=environment();e.setDetail({...detail(),[key]:value});await e.open();assert.equal(e.control('disputeMeta').children.length,0);assert.equal(e.control('disputeReview').disabled,true)});
test('Current round changing after review invalidates confirmation without a write',async()=>{const e=environment();await compose(e);e.setDetail(detail({version:'9007199254740994'}));await e.confirm();assert.equal(writes(e).length,0);assert.match(e.control('disputeMessage').textContent,/conflict/)});
test('Form edits including programmatic edits invalidate confirmation',async()=>{for(const event of [true,false]){const e=environment();await compose(e);e.control('disputeSummary').value='different';if(event)e.control('disputeSummary').oninput();await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.control('disputeConfirm').hidden,true)}});
test('Admin can decide with no evidence and exact reason/version/round payload',async()=>{const e=environment({admin:true});await e.open();assert.equal(e.control('disputeForm').hidden,true);assert.deepEqual(e.control('disputeOperation').children.map(n=>n.value),['owner','applicant']);field(e,'disputeReason','Administrator finding');await e.control('disputeReviewDecision').onclick();assert.equal(writes(e).length,0);e.queue({detail:detail({admin:true,status:'resolved',decision:'owner',reason:'Administrator finding',winner_id:'1',version:'9007199254740994',can_reopen:true})},'/decision','POST');await e.confirm();assert.deepEqual(JSON.parse(writes(e)[0].options.body),{version:'9007199254740993',round_number:'1',action:'owner',reason:'Administrator finding',winner_claim_id:null});assert.equal(e.control('disputeOperation').children[0].value,'reopen')});
test('Admin requires reason and applicant Claim selection',async()=>{const e=environment({admin:true});await e.open();await e.control('disputeReviewDecision').onclick();assert.equal(e.control('disputeConfirm').hidden,true);assert.equal(writes(e).length,0)});
test('Admin additional round action is available only while reviewing',async()=>{const e=environment({admin:true}),d=detail({admin:true});d.round.phase=d.round_phase='reviewing';e.setDetail(d);await e.open();assert.deepEqual(e.control('disputeOperation').children.map(n=>n.value),['owner','applicant','request_evidence'])});
test('Disallowed resolved case never offers reopen',async()=>{const e=environment({admin:true});e.setDetail(detail({admin:true,status:'resolved',decision:'owner',reason:'Final',winner_id:'1'}));await e.open();assert.equal(e.control('disputeOperation').children.length,0);assert.equal(e.control('disputeReviewDecision').disabled,true)});
test('Admin reviewed summary publication is explicit and preserves originals',async()=>{const e=environment({admin:true});e.setDetail(completed(true));await e.open();const input=e.control('disputePublishSummary_51');field(e,input.id,'Reviewed for other party');await e.history.querySelectorAll('button').find(n=>n.dataset.disputePublish).onclick();assert.equal(writes(e).length,0);const d=completed(true);d.version='9007199254740995';d.evidence[0].published_summary='Reviewed for other party';d.evidence[0].published_at=now;d.evidence[0].can_publish=false;e.queue({detail:d},'/publish','POST');await e.confirm();assert.equal(writes(e).length,1);assert.deepEqual(JSON.parse(writes(e)[0].options.body),{version:'9007199254740994',round_number:'1',summary:'Reviewed for other party'});assert.match(e.history.textContent,/My private explanation/);assert.match(e.history.textContent,/Reviewed for other party/)});
test('No attachment/read mutations ever happen automatically on detail load',async()=>{const e=environment({admin:true});e.setDetail(completed(true));await e.open();assert.equal(e.calls.length,1);assert.equal(writes(e).length,0);assert.doesNotMatch(e.calls[0].url,/attachment|notifications/)});
test('Eligible options support a scanned cursor after filtered-out tail rows',async()=>{const e=environment();e.queue({items:[option({claim_id:'50'})],next_after:'40',can_write:true,viewer_user_id:'2'},'/options?');await e.component.refresh();assert.equal(e.control('disputeOptionNext').disabled,false);e.queue({items:[],next_after:'30',can_write:true,viewer_user_id:'2'},'/options?');await e.control('disputeOptionNext').onclick();assert.equal(e.control('selfDisputes').hidden,false);assert.equal(e.control('disputeOptionNext').disabled,false);assert.equal(e.control('disputeOptionPrevious').disabled,false)});
test('An empty last filtered page keeps Previous accessible',async()=>{const e=environment();e.queue({items:[],next_after:'40',can_write:true,viewer_user_id:'2'},'/options?');await e.component.refresh();e.queue({items:[],next_after:null,can_write:true,viewer_user_id:'2'},'/options?');await e.control('disputeOptionNext').onclick();assert.equal(e.control('selfDisputes').hidden,false);assert.equal(e.control('disputeOptionPrevious').disabled,false)});
test('A historical option may have no current owner and remains non-actionable',async()=>{const e=environment();e.setOption(option({owner:null,eligible:false,can_appeal:false,can_acknowledge:false}));await e.openOption();assert.match(e.control('disputeMeta').textContent,/—/);assert.equal(e.control('disputeForm').hidden,true);assert.equal(e.control('disputeAccept').hidden,true)});
test('Maximum reason event prefix and legacy DTO text bounds are accepted',async()=>{const e=environment();const d=detail();d.events=[{id:'1',kind:'resolved',note:'Reason: '+'a'.repeat(4000),created_at:now,round_number:'1'}];d.individual.model='a'.repeat(1000);d.claims[0].applicant_name='a'.repeat(200);e.setDetail(d);await e.open();assert.equal(e.control('disputeForm').hidden,false);assert.match(e.history.textContent,/Reason:/)});
test('Unavailable session storage prevents any mutation before transmission',async()=>{const e=environment({storageDenied:true});await compose(e);await e.confirm();assert.equal(writes(e).length,0);assert.match(e.control('disputeMessage').textContent,/storage/)});
for(const id of [31,9007199254740993,'01','0','9223372036854775808'])test('Public destination entrypoints reject invalid/non-string ID '+id,async()=>{const e=environment();await e.component.openDispute(id);await e.component.openDisputeOption(id);assert.equal(e.calls.length,0)});
for(const status of [401,403])test('Admin access denial '+status+' notifies the Console to purge other panels',async()=>{const e=environment({admin:true});e.queue(denied(status),'/31');await e.open();assert.equal(e.denials.length,1);assert.equal(e.denials[0].status,status);assert.equal(e.dialog.open,false)});
for(const change of ['account','signout','popstate','pagehide','close'])test('Pending mutation after '+change+' cannot re-open a private case or restore drafts',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/evidence','POST');const work=e.confirm();await e.flush();assert.equal(writes(e).length,1);if(change==='close')e.dismiss();else if(['popstate','pagehide'].includes(change))e.event(change);else e.changeAccount(change==='signout'?null:account('3'));const count=e.calls.length;held.resolve({detail:completed()});await work;assert.equal(e.dialog.open,false);assert.equal(e.history.children.length,0);assert.equal(e.control('disputeExplanation').value,'');if(change!=='close')assert.equal(e.calls.length,count)});
test('Newer case lists win over an older delayed list success or access rejection',async()=>{for(const value of [{items:[caseRow()],next_after:null,can_write:true,viewer_user_id:'2'},denied(403)]){const e=environment(),held=deferred();e.queue(held.promise,'?limit=25&status=open');const work=e.component.refresh();e.setCases([caseRow({id:'32'})]);await e.component.refresh();held.resolve(value);await work;assert.equal(e.list.children[0].dataset.disputeCase,'32')}});
test('A delayed successful mutation cannot replace a newer explicitly refreshed list',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/evidence','POST');const work=e.confirm();await e.flush();e.setCases([caseRow({id:'32'})]);await e.component.refresh();const count=e.calls.length;held.resolve({detail:completed()});await work;assert.equal(e.calls.length,count);assert.equal(e.list.children[0].dataset.disputeCase,'32')});
test('Closing an unknown-outcome case retains the retry marker after reopening',async()=>{const e=environment();await compose(e);e.queue(Error('lost'),'/evidence','POST');await e.confirm();e.dismiss();await e.open();assert.equal(e.control('disputeReview').disabled,true);assert.equal(e.control('disputeCheck').hidden,false);assert.equal(e.storage.size,1);assert.equal(writes(e).length,1)});
test('The retry marker survives reconstruction without persisting evidence or text',async()=>{const storage=new Map(),e=environment({storage});await compose(e);e.queue(Error('lost'),'/evidence','POST');await e.confirm();assert.doesNotMatch([...storage.values()].join(''),/private explanation|Summary for review/);const another=environment({storage});await another.open();assert.equal(another.control('disputeReview').disabled,true);assert.equal(another.control('disputeCheck').hidden,false)});
test('Empty required draft can be corrected locally without a server mutation or forced reload',async()=>{const e=environment();await e.openOption();await e.review();assert.equal(e.control('disputeReview').disabled,false);field(e,'disputeExplanation','private');field(e,'disputeSummary','summary');e.control('disputeAttachment').files=[file()];await e.review();assert.equal(e.control('disputeConfirm').hidden,false);assert.equal(writes(e).length,0)});
test('Attachment is fetched privately only on an explicit download and URL revoked on Close',async()=>{const e=environment();e.setDetail(completed());await e.open();assert.equal(e.created.length,0);e.queue(file(),'/attachment');await e.history.querySelectorAll('button').find(n=>n.dataset.disputeAttachment).onclick();assert.match(e.calls.at(-1).url,/ownership-disputes\/evidence\/51\/attachment$/);assert.equal(e.created.length,1);e.dismiss();assert.deepEqual(e.revoked,['blob:fixture-0']);assert.equal(e.history.children.length,0)});
for(const interruption of ['close','popstate','pagehide','signout','account'])test('Attachment response after '+interruption+' never creates an object URL',async()=>{const e=environment(),held=deferred();e.setDetail(completed());await e.open();e.queue(held.promise,'/attachment');const work=e.history.querySelectorAll('button').find(n=>n.dataset.disputeAttachment).onclick();await e.flush();if(interruption==='close')e.dismiss();else if(['popstate','pagehide'].includes(interruption))e.event(interruption);else e.changeAccount(interruption==='signout'?null:account('3'));held.resolve(file());await work;assert.equal(e.created.length,0);assert.equal(e.dialog.open,false)});
for(const blob of [new Blob(['html'],{type:'text/html'}),new Blob([],{type:'application/pdf'}),new Blob([new Uint8Array(12*1024*1024+1)],{type:'application/pdf'})])test('Unrecognized or oversized private attachment never becomes a download URL',async()=>{const e=environment();e.setDetail(completed());await e.open();e.queue(blob,'/attachment');await e.history.querySelectorAll('button').find(n=>n.dataset.disputeAttachment).onclick();assert.equal(e.created.length,0);assert.equal(e.control('disputeReview').disabled,true)});


test('Legacy storage preflight is a distinct operator blocker and never triggers retry automatically',async()=>{const e=environment();await compose(e);e.queue(denied(409,'dispute_storage_preflight_required'),'/evidence','POST');await e.confirm();assert.match(e.control('disputeMessage').textContent,/storage_preflight/);assert.equal(e.control('disputeReview').disabled,true);assert.equal(e.storage.size,0);assert.equal(writes(e).length,1)});
