const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync('app/src/ygc/static/user_view_html.html','utf8');
const start=html.indexOf('function discoveryOwnerHtml(');
const source=html.slice(start,html.indexOf('\n}',start)+2);
const context=vm.createContext({esc:s=>String(s).replaceAll('<','&lt;').replaceAll('>','&gt;')});
vm.runInContext(source,context);
const render=item=>context.discoveryOwnerHtml(item);
assert.equal(render({current_owner_user_id:null}), '');
const followed=render({current_owner_user_id:17,current_owner_name:'<Owner>',current_owner_following:true});
assert.ok(followed.includes('href="/users/17"'));
assert.ok(followed.includes('event.stopPropagation()'));
assert.ok(followed.includes('&lt;Owner&gt;'));
assert.ok(followed.includes('>Following</span>'));
assert.ok(!render({current_owner_user_id:17,current_owner_name:'Owner',current_owner_following:false}).includes('>Following</span>'));
console.log('New Discovery current owner links and Following: passed');
