const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const assets=path.join(__dirname,'../src/ygc/static');
const account=(id='1',verified=true,status='active')=>({user:{app_user_id:'uuid-'+id,display_name:'Member '+id,role:'member',status},identity:{email_verified:verified}});
const guitar=(extra={})=>({id:'9007199254741009',manufacturer:'Fixture maker',model:'Fixture guitar',finish:null,year:'1965',serial_number:'S1',photo:null,...extra});
const favorites=(extra={})=>({items:[guitar()],total:'1',next_after:null,...extra});
const preferences=(extra={})=>({profile_revision:'9007199254740993',fields:{birth_visibility:'Private',residence_visibility:'Private',bio_visibility:'Public',avatar_visibility:'Public'},...extra});
const success=(favorite=false,id=guitar().id)=>({individual_id:id,favorite});
const denied=(httpStatus=403,code='account_inactive')=>({httpStatus,code});
const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}};
function environment({kind='favorites',initial=account(),fullPage=false}={}){
 const ids=new Map(),listeners={};
 class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.dataset={};this.value='';this.hidden=false;this.open=false;this.disabled=false;this._text=''}
  set id(value){this._id=value;ids.set(value,this)}get id(){return this._id}
  set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(n=>n.textContent).join('')}
  set innerHTML(_){throw Error('Private values must remain text')}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this._text='';this.children=nodes}
  setAttribute(key,value){this[key]=value}removeAttribute(key){delete this[key]}
  addEventListener(key,fn){(this.listeners[key]??=[]).push(fn)}dispatchEvent(event){for(const fn of this.listeners[event.type]||[])fn(event)}
  all(){return this.children.flatMap(n=>[n,...n.all()])}querySelectorAll(s){return this.all().filter(n=>s.split(',').map(t=>t.toUpperCase()).includes(n.tagName))}
  reset(){for(const n of this.all())n.value=''}focus(){document.activeElement=this}
 }
 const document={body:new Element('body'),documentElement:{lang:'en'},createElement:tag=>new Element(tag),getElementById:id=>ids.get(id)};
 for(const match of fs.readFileSync(path.join(assets,'cloud_account_html.html'),'utf8').matchAll(/<(\w+)[^>]*\bid="([^"]+)"/g)){const n=new Element(match[1]);n.id=match[2];document.body.append(n)}
 const detail=new Element('section');detail.id='detailFavorite';document.body.append(detail);
 let busy=false,component,logoutResult=null,listPage=favorites(),profile=preferences(),favorite=false,writeAllowed=true;const calls=[],replies=[],cleared=[],identityListeners=[];
 const context=vm.createContext({document,URL,URLSearchParams,Intl,Date,console,location:{search:'',origin:'https://ygc.example'},YGCI18n:{t:(key,params={})=>key+(Object.keys(params).length?JSON.stringify(params):'')}});
 context.window=context;context.addEventListener=(key,fn)=>(listeners[key]??=[]).push(fn);
 context.YGCOverlays={open(dialog){dialog.open=true},close(dialog){dialog.open=false;dialog.dispatchEvent({type:'ygc:closed'})}};
 const client={onIdentityChanged(listener){identityListeners.push(listener);return ()=>{}},signedIn:Boolean(initial),account:initial,documents:async()=>({terms:{version:'t'},privacy:{version:'p'}}),restore:async()=>client.account,
  async signIn(){client.signedIn=true;return client.account=account('1',false)},async logout(){await logoutResult;client.signedIn=false;client.account=null},async refreshVerification(){return client.account=account()},
  async authorizedFetch(url,options={},verified){calls.push({url,options,verified,owner:client.account?.user?.app_user_id});const i=replies.findIndex(r=>(!r.match||url.includes(r.match))&&(!r.method||r.method===(options.method||'GET')));let value;
   if(i>=0)value=await replies.splice(i,1)[0].value;
   else{assert.equal(options.method||'GET','GET','Writes require explicit fixture');value=url.startsWith('/api/auth/favorites?')?listPage:url==='/api/auth/profile/visibility'?profile:success(favorite,url.split('/').at(-1))}
   if(value instanceof Error)throw value;return value?.httpStatus?{ok:false,status:value.httpStatus,json:async()=>({detail:{code:value.code,message:'SECRET SQL'}})}:{ok:true,json:async()=>value};
  }};
 for(const filename of ['cloud-account-favorites.js','cloud-account-visibility.js'])vm.runInContext(fs.readFileSync(path.join(assets,filename),'utf8').replaceAll('export function','function'),context);
 const args={auth:()=>client,state:()=>client.account,busy:()=>busy,work:async fn=>{busy=true;component?.render();try{return await fn()}finally{busy=false;component?.render()}}};
 let ready=Promise.resolve();
 if(fullPage){
  const noOp=()=>({render(){},clear(){cleared.push(true)},refresh:async()=>{},refreshHistory:async()=>{},failed(){},setCatalogIntent(){}});
  Object.assign(context,{loadCloudAuth:async()=>client,createAvatar:noOp,createProfile:noOp,createGuitars:noOp,createClaims:noOp,createOwnership:noOp,createApplications:noOp,createDisputes:noOp,createIdentityCorrections:noOp,createNotifications:noOp,readCatalogIntent:()=>null,readClaimIntent:()=>null,readOwnershipIntent:()=>null});
  ready=vm.runInContext('(async()=>{'+fs.readFileSync(path.join(assets,'cloud-account-page.js'),'utf8').replace(/^import .*;\n/gm,'')+'})()',context);
 }else component=kind==='favorites'?context.createFavorites(args):kind==='visibility'?context.createVisibility(args):context.createFavoriteControl({...args,root:detail,document,t:context.YGCI18n.t,canWrite:()=>writeAllowed});
 const control=id=>ids.get(id);
 return {component,context,client,control,calls,ready,cleared,root:detail,
  sdkSwitch(next){client.account=null;client.signedIn=Boolean(next);for(const listener of identityListeners)listener()},
  queue(value,match=null,method=null){replies.push({value,match,method})},setList(value){listPage=value},setProfile(value){profile=value},setFavorite(value){favorite=value},setWriteAllowed(value){writeAllowed=value;component.render()},holdLogout(value){logoutResult=value},
  changeAccount(next){client.account=next;client.signedIn=Boolean(next);component?.render()},event(key,event={}){return Promise.all((listeners[key]||[]).map(fn=>fn(event)))},
  choose(key,value){const input=control('visibility_'+key);input.value=value;input.onchange()},submit(){return control('visibilityForm').onsubmit({preventDefault(){}})},
  async flush(){for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve))}
 };
}
const writes=e=>e.calls.filter(c=>c.options.method==='PUT');
for(const initial of [null,account('1',false),account('1',true,'disabled'),account('1',true,'banned')])test('Ineligible accounts cannot read favorites or preferences',async()=>{for(const kind of ['favorites','visibility']){const e=environment({kind,initial});await e.component.refresh();assert.equal(e.calls.length,0);assert.equal(e.control(kind==='favorites'?'selfFavorites':'selfVisibility').hidden,true)}});

test('Favorites list is private bounded exact-ID text with only public-detail links',async()=>{const e=environment();await e.component.refresh();assert.equal(e.control('favoritesList').children[0].dataset.favoriteId,guitar().id);assert.match(e.control('favoritesCount').textContent,/"1"/);const link=e.control('favoritesList').querySelectorAll('a')[0];assert.equal(link.href,'/guitars/'+guitar().id);assert.equal(e.control('favoritesList').querySelectorAll('img,button').length,0);assert.equal(e.calls[0].url,'/api/auth/favorites?limit=25');assert.equal(e.calls[0].verified,true);for(const key of ['cache','credentials','redirect'])assert.equal(e.calls[0].options[key],{cache:'no-store',credentials:'omit',redirect:'error'}[key]);assert.equal(writes(e).length,0)});
test('Favorites Previous and Next use descending exact string keyset pages',async()=>{const e=environment();e.setList(favorites({next_after:guitar().id,total:'27'}));await e.component.refresh();e.queue(favorites({items:[guitar({id:'9007199254740993'})]}),'after=');await e.control('favoritesNext').onclick();assert.equal(e.control('favoritesList').children.length,1);assert.equal(e.control('favoritesPrevious').disabled,false);assert.match(e.calls.at(-1).url,/after=9007199254741009&limit=25$/);await e.control('favoritesPrevious').onclick();assert.equal(e.control('favoritesList').children[0].dataset.favoriteId,guitar().id);assert.equal(e.control('favoritesPrevious').disabled,true)});
test('Favorite text is inert and 200 Unicode code points remain intact',async()=>{const e=environment();e.setList(favorites({items:[guitar({model:'<img src=x onerror=secret>',manufacturer:'🎸'.repeat(200)})]}));await e.component.refresh();assert.match(e.control('favoritesList').textContent,/<img/);assert.equal(e.control('favoritesList').querySelectorAll('img,script').length,0)});
for(const patch of [{id:9007199254741009},{id:'1\n'},{id:'01'},{id:'9223372036854775808'},{photo:'https://private'},{owner:'SECRET'},{model:'🎸'.repeat(201)},{year:1960},{manufacturer:'bad\ntext'},{finish:'\ud800'}])test('Malformed or extra favorite fields fail closed '+Object.keys(patch),async()=>{const e=environment();e.setList(favorites({items:[guitar(patch)]}));await e.component.refresh();assert.equal(e.control('favoritesList').children.length,0);assert.equal(e.control('favoritesCount').textContent,'')});
for(const page of [favorites({total:1}),favorites({total:'01'}),favorites({total:'9223372036854775808'}),favorites({items:[guitar(),guitar()]}),favorites({items:[],next_after:'1'}),favorites({next_after:'1'}),favorites({items:Array(26).fill(guitar())}),favorites({private_email:'secret'})])test('Malformed favorite page/count/cursor is rejected',async()=>{const e=environment();e.setList(page);await e.component.refresh();assert.equal(e.control('favoritesList').children.length,0);assert.equal(e.control('favoritesNext').disabled,true)});
for(const type of ['signout','account','unverified','disabled','popstate','pagehide'])test('Pending private reads cannot return after '+type,async()=>{for(const kind of ['favorites','visibility']){const e=environment({kind}),held=deferred();e.queue(held.promise);const job=e.component.refresh();if(['popstate','pagehide'].includes(type))e.event(type);else e.changeAccount(type==='signout'?null:account(type==='account'?'2':'1',type!=='unverified',type==='disabled'?'disabled':'active'));held.resolve(kind==='favorites'?favorites():preferences());await job;assert.equal(e.control(kind==='favorites'?'favoritesList':'visibilityValues').children.length,0)}});
test('A newer private list wins over late older response',async()=>{const e=environment(),held=deferred();e.queue(held.promise);const old=e.component.refresh();e.setList(favorites({items:[guitar({model:'NEW'})]}));await e.component.refresh();held.resolve(favorites());await old;assert.match(e.control('favoritesList').textContent,/NEW/)});

test('Guests get only an account entrance and no favorite API request',async()=>{const e=environment({kind:'control',initial:null});await e.component.select(guitar().id);assert.equal(e.root.hidden,false);assert.equal(e.control('favoriteToggle').hidden,true);assert.equal(e.control('favoriteAccount').hidden,false);assert.equal(e.control('favoriteAccount').href,'/account#selfFavorites');await e.control('favoriteToggle').onclick();assert.equal(e.calls.length,0)});
test('Favorite toggles only on explicit click and duplicate clicks cannot reverse a pending write',async()=>{const e=environment({kind:'control'});await e.component.select(guitar().id);assert.equal(writes(e).length,0);const held=deferred();e.queue(held.promise,null,'PUT');const job=e.control('favoriteToggle').onclick();e.control('favoriteToggle').onclick();assert.equal(writes(e).length,1);assert.deepEqual(JSON.parse(writes(e)[0].options.body),{favorite:true});held.resolve(success(true));await job;assert.equal(e.control('favoriteToggle')['aria-pressed'],'true');e.queue(success(false),null,'PUT');await e.control('favoriteToggle').onclick();assert.equal(writes(e).length,2);assert.equal(e.control('favoriteToggle')['aria-pressed'],'false')});
for(const result of [Error('SECRET response lost'),denied(500),denied(503),{},success(true,'2'),success('true'),{...success(true),private_email:'secret'}])test('Uncertain favorite result requires successful explicit Refresh',async()=>{const e=environment({kind:'control'});await e.component.select(guitar().id);e.queue(result,null,'PUT');await e.control('favoriteToggle').onclick();assert.equal(e.control('favoriteToggle').disabled,true);assert.match(e.control('favoriteStatus').textContent,/uncertain/);await e.control('favoriteToggle').onclick();assert.equal(writes(e).length,1);e.queue(denied(503));await e.control('favoriteRefresh').onclick();assert.equal(e.control('favoriteToggle').disabled,true);e.setFavorite(true);await e.control('favoriteRefresh').onclick();assert.equal(e.control('favoriteToggle').disabled,false);assert.equal(e.control('favoriteToggle')['aria-pressed'],'true')});
for(const status of [400,401,403,404,409,422])test('Favorite definitive rejection '+status+' clears selected state until a new read',async()=>{const e=environment({kind:'control'});await e.component.select(guitar().id);e.queue(denied(status),null,'PUT');await e.control('favoriteToggle').onclick();assert.equal(e.control('favoriteToggle').disabled,true);assert.equal(e.control('favoriteToggle')['aria-pressed'],'false');assert.doesNotMatch(e.control('favoriteStatus').textContent,/SECRET|uncertain/)});
for(const action of ['navigation','account','signout'])test('Late favorite read/write after '+action+' cannot restore private state',async()=>{for(const operation of ['GET','PUT']){const e=environment({kind:'control'});await e.component.select(guitar().id);const held=deferred();e.queue(held.promise,null,operation);const job=operation==='GET'?e.component.refresh():e.control('favoriteToggle').onclick();if(action==='navigation')e.component.clear();else e.changeAccount(action==='signout'?null:account('2'));held.resolve(success(true));await job;assert.equal(e.root.hidden,true);assert.equal(e.control('favoriteToggle')['aria-pressed'],'false');assert.equal(e.control('favoriteStatus').textContent,'')}});
test('Read-only permits favorite reads while explicit changes are disabled',async()=>{const e=environment({kind:'control'});await e.component.select(guitar().id);e.setWriteAllowed(false);await e.control('favoriteToggle').onclick();assert.equal(writes(e).length,0);await e.control('favoriteRefresh').onclick();assert.equal(e.calls.length,2);assert.equal(e.control('favoriteToggle').disabled,true)});

test('Existing preference defaults are displayed without saving or publication',async()=>{const e=environment({kind:'visibility'});await e.component.refresh();assert.match(e.control('visibilityValues').textContent,/option_Public/);assert.equal(writes(e).length,0);e.control('visibilityEdit').onclick();assert.equal(e.control('visibilityDialog').open,true);assert.equal(e.control('visibilitySave').disabled,true);await e.submit();assert.equal(writes(e).length,0);assert.match(e.control('selfVisibility').textContent,/visibility.notice/)});
test('Unknown saved visibility is unselected until every null choice is made explicitly',async()=>{const e=environment({kind:'visibility'});e.setProfile(preferences({fields:{birth_visibility:null,residence_visibility:null,bio_visibility:'Public',avatar_visibility:'Public'}}));await e.component.refresh();e.control('visibilityEdit').onclick();assert.equal(e.control('visibility_birth_visibility').value,'');assert.equal(e.control('visibilitySave').disabled,true);e.choose('birth_visibility','Private');await e.submit();assert.equal(writes(e).length,0);e.choose('residence_visibility','Followers');assert.equal(e.control('visibilitySave').disabled,false);e.queue(preferences({profile_revision:'9007199254740994',fields:{birth_visibility:'Private',residence_visibility:'Followers',bio_visibility:'Public',avatar_visibility:'Public'}}),null,'PUT');await e.submit();assert.equal(writes(e).length,1);assert.equal(JSON.parse(writes(e)[0].options.body).revision,'9007199254740993');assert.match(e.control('visibilityStatus').textContent,/saved/)});
test('Cancel or overlay dismissal erases staged choices without write',async()=>{for(const dismiss of ['cancel','overlay']){const e=environment({kind:'visibility'});await e.component.refresh();e.control('visibilityEdit').onclick();e.choose('bio_visibility','Private');if(dismiss==='cancel')e.control('visibilityCancel').onclick();else e.context.YGCOverlays.close(e.control('visibilityDialog'));await e.submit();assert.equal(writes(e).length,0);assert.equal(e.control('visibility_bio_visibility').value,'');e.control('visibilityEdit').onclick();assert.equal(e.control('visibility_bio_visibility').value,'Public')}});
test('Visibility duplicate Save sends exactly one complete strict preferences request',async()=>{const e=environment({kind:'visibility'});await e.component.refresh();e.control('visibilityEdit').onclick();e.choose('bio_visibility','Followers');const held=deferred();e.queue(held.promise,null,'PUT');const job=e.submit();e.submit();assert.equal(writes(e).length,1);const body=JSON.parse(writes(e)[0].options.body);assert.deepEqual(Object.keys(body).sort(),['fields','revision']);assert.equal(body.fields.bio_visibility,'Followers');assert.equal(writes(e)[0].url,'/api/auth/profile/visibility');held.resolve(preferences({profile_revision:'9007199254740994',fields:body.fields}));await job;assert.equal(e.control('visibilityDialog').open,false);assert.equal(e.control('visibilityEdit').disabled,false)});
for(const result of [Error('SECRET response lost'),denied(500),denied(503),{},preferences(),preferences({profile_revision:'0'})])test('Uncertain visibility update never retries and blocks Edit until explicit successful refresh',async()=>{const e=environment({kind:'visibility'});await e.component.refresh();e.control('visibilityEdit').onclick();e.choose('bio_visibility','Private');e.queue(result,null,'PUT');await e.submit();assert.equal(e.control('visibilityEdit').disabled,true);assert.equal(e.control('visibilityValues').children.length,0);assert.match(e.control('visibilityStatus').textContent,/uncertain/);e.control('visibilityEdit').onclick();await e.submit();assert.equal(writes(e).length,1);e.queue(denied(503));await e.control('visibilityRefresh').onclick();assert.equal(e.control('visibilityEdit').disabled,true);await e.control('visibilityRefresh').onclick();assert.equal(e.control('visibilityEdit').disabled,false)});
test('Visibility conflict requires an explicit fresh revision and review; no silent CAS retry',async()=>{const e=environment({kind:'visibility'});await e.component.refresh();e.control('visibilityEdit').onclick();e.choose('avatar_visibility','Private');e.queue(denied(409),null,'PUT');await e.submit();assert.match(e.control('visibilityStatus').textContent,/conflict/);assert.equal(e.control('visibilityEdit').disabled,true);assert.equal(writes(e).length,1);e.setProfile(preferences({profile_revision:'9223372036854775807'}));await e.control('visibilityRefresh').onclick();e.control('visibilityEdit').onclick();assert.equal(e.control('visibility_avatar_visibility').value,'Public');assert.equal(e.control('visibilitySave').disabled,true)});
for(const action of ['popstate','pagehide','account','signout'])test('Late visibility save after '+action+' cannot restore values',async()=>{const e=environment({kind:'visibility'});await e.component.refresh();e.control('visibilityEdit').onclick();e.choose('bio_visibility','Private');const held=deferred();e.queue(held.promise,null,'PUT');const job=e.submit();if(action==='account'||action==='signout')e.changeAccount(action==='account'?account('2'):null);else e.event(action);held.resolve(preferences({fields:{...preferences().fields,bio_visibility:'Private'}}));await job;assert.equal(e.control('visibilityValues').children.length,0);assert.equal(e.control('visibilityDialog').open,false);assert.equal(e.control('visibilityStatus').textContent,'')});
for(const value of [preferences({profile_revision:'0'}),preferences({profile_revision:'1\n'}),preferences({profile_revision:1}),preferences({profile_revision:'01'}),preferences({profile_revision:'9223372036854775808'}),preferences({fields:{...preferences().fields,bio_visibility:'public'}}),preferences({private_email:'secret'}),preferences({fields:{...preferences().fields,location_country:'secret'}})])test('Malformed visibility DTO fails closed without exposing raw legacy data',async()=>{const e=environment({kind:'visibility'});e.setProfile(value);await e.component.refresh();assert.equal(e.control('visibilityValues').children.length,0);assert.equal(e.control('visibilityEdit').disabled,true)});
test('Account shell clears private sections before delayed or failed logout, without reloading them',async()=>{for(const fail of [false,true]){const e=environment({fullPage:true});await e.ready;assert.equal(e.control('favoritesList').children.length,1);assert.equal(e.control('visibilityValues').children.length,8);const held=deferred();e.holdLogout(held.promise.then(()=>{if(fail)throw Error('Logout failed')}));const clears=e.cleared.length;const job=e.control('signOut').onclick();assert.ok(e.cleared.length-clears>=9);assert.equal(e.control('accountSummary').hidden,true);assert.equal(e.control('favoritesList').children.length,0);assert.equal(e.control('visibilityValues').children.length,0);held.resolve();await job;assert.equal(e.control('favoritesList').children.length,0);assert.equal(e.control('visibilityValues').children.length,0);assert.equal(writes(e).length,0)}});
test('Feature localization keys match English/Japanese and do not translate wire enums',()=>{const en=JSON.parse(fs.readFileSync(path.join(assets,'locales/en.json'))),ja=JSON.parse(fs.readFileSync(path.join(assets,'locales/ja.json')));const keys=Object.keys(en).filter(k=>/^(favorites|visibility)\./.test(k));assert.deepEqual(keys,Object.keys(ja).filter(k=>/^(favorites|visibility)\./.test(k)));assert.match(en['visibility.notice'],/Avatar settings apply to signed-in members/);assert.match(en['visibility.notice'],/Other profile settings do not publish/);assert.match(en['favorites.private_notice'],/Only you/);for(const value of ['Public','Members','Followers','Private'])assert.ok(en['visibility.option_'+value]&&ja['visibility.option_'+value]);const source=fs.readFileSync(path.join(assets,'cloud-account-favorites.js'),'utf8');assert.doesNotMatch(source,/innerHTML|insertAdjacentHTML|localStorage|viewer_user_id|\/api\/users/)});

test('External SDK identity changes clear every account-shell private component',async()=>{
 const e=environment({fullPage:true});await e.ready;const before=e.cleared.length;e.sdkSwitch(account('2'));
 assert.equal(e.control('selfFavorites').hidden,true);assert.equal(e.control('selfVisibility').hidden,true);assert.equal(e.control('accountSummary').hidden,true);assert.ok(e.cleared.length-before>=9);assert.match(e.control('status').textContent,/session_changed/);assert.equal(writes(e).length,0);
});
test('BFCache account return rechecks canonical identity before refreshing private sections',async()=>{
 const e=environment({fullPage:true});await e.ready;await e.event('pagehide');assert.equal(e.control('favoritesList').children.length,0);assert.equal(e.control('visibilityValues').children.length,0);const held=deferred();e.client.restore=()=>held.promise;const show=e.event('pageshow',{persisted:true});assert.equal(e.control('favoritesList').children.length,0);assert.equal(e.control('selfFavorites').hidden,true);e.client.account=account('2');e.setList(favorites({items:[guitar({model:'B guitar'})]}));held.resolve(e.client.account);await show;assert.match(e.control('favoritesList').textContent,/B guitar/);assert.equal(e.calls.at(-1).owner,'uuid-2');assert.equal(writes(e).length,0);
});
test('A late BFCache restore after a newer pagehide cannot reload private sections',async()=>{
 const e=environment({fullPage:true});await e.ready;await e.event('pagehide');const held=deferred();e.client.restore=()=>held.promise;const show=e.event('pageshow',{persisted:true});await e.event('pagehide');const calls=e.calls.length;held.resolve(e.client.account);await show;assert.equal(e.control('favoritesList').children.length,0);assert.equal(e.control('visibilityValues').children.length,0);assert.equal(e.calls.length,calls);
});
