const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const assets=path.join(__dirname,'../src/ygc/static');
const account=(id='1',verified=true,status='active')=>({user:{app_user_id:'uuid-'+id,display_name:'Member '+id,role:'member',status},identity:{email_verified:verified}});
const guitar=(id='12',extra={})=>({id,manufacturer:'Maker',model:'Model',year:'1965',serial_number:'SERIAL-'+id,...extra});
const listing=(extra={})=>({id:'31',individual:guitar(),occurred_at:'2020-01-01',...extra});
const correction=(extra={})=>({id:'41',target_claim_id:'31',individual_id:'12',body:'Corrected typo',occurred_at:'2020-01-01',created_at:'2026-10-07T01:00:00Z',status:'active',verification_status:'positive',changes:[{field_name:'model',old_value:'Model',new_value:'Corrected'}],...extra});
const detail=(extra={})=>({listing:{id:'31',individual_id:'12',occurred_at:'2020-01-01'},individual:guitar(),items:[],next_after:null,revision:'a'.repeat(64),can_write:true,...extra});
const success=(extra={})=>({correction:correction(),detail:detail({individual:guitar('12',{model:'Corrected'}),items:[correction()],revision:'b'.repeat(64)}),...extra});
const denied=(status=403,code='account_inactive',raw='SECRET DUPLICATE #987654321')=>({httpStatus:status,code,raw});
const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}};
function environment({initial=account(),fullPage=false,storage=new Map(),storageDenied=false}={}){
 const ids=new Map(),listeners={};
 class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.dataset={};this.style={};this.value='';this.hidden=false;this.open=false;this.disabled=false;this._text='';this.classList={add(){},remove(){}};this.isConnected=true;this.tabIndex=0}
  set id(value){this._id=value;ids.set(value,this)}get id(){return this._id}
  set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(n=>n.textContent).join('')}
  set innerHTML(value){throw Error('Ownership must be text-only')}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this._text='';this.children=nodes}
  setAttribute(key,value){this[key]=value}removeAttribute(key){delete this[key]}hasAttribute(key){return key in this}
  addEventListener(key,fn){(this.listeners[key]??=[]).push(fn)}dispatchEvent(event){for(const fn of this.listeners[event.type]||[])fn(event)}
  all(){return this.children.flatMap(n=>[n,...n.all()])}contains(n){return n===this||this.all().includes(n)}
  querySelectorAll(selector){return this.all().filter(n=>selector.split(',').map(t=>t.toUpperCase()).includes(n.tagName))}querySelector(s){return this.querySelectorAll(s)[0]||null}
  reset(){for(const n of this.all())n.value=''}focus(){document.activeElement=this}closest(){return null}getClientRects(){return this.hidden?[]:[this.getBoundingClientRect()]}
  getBoundingClientRect(){return {left:20,right:600,top:20,bottom:600}}showModal(){this.open=true;this.opens=(this.opens||0)+1}close(){this.open=false}
 }
 const document={body:new Element('body'),documentElement:{lang:'en'},createElement:tag=>new Element(tag),getElementById:id=>ids.get(id),addEventListener(key,fn){(listeners[key]??=[]).push(fn)}};
 for(const match of fs.readFileSync(path.join(assets,'cloud_account_html.html'),'utf8').matchAll(/<(\w+)[^>]*\bid="([^"]+)"/g)){const n=new Element(match[1]);n.id=match[2];document.body.append(n)}
 let state=initial,busy=false,component,args,updates=0,defaultDetail=detail(),defaultListings=[listing()];const calls=[],replies=[];
 async function response(value){const data=await value;if(data instanceof Error)throw data;return data?.httpStatus?{ok:false,status:data.httpStatus,json:async()=>({detail:{code:data.code,message:data.raw,individual_id:'987654321'}})}:{ok:true,json:async()=>data}}
 const client={signedIn:Boolean(initial),account:initial,documents:async()=>({terms:{version:'t'},privacy:{version:'p'}}),restore:async()=>initial,
  async signIn(){this.signedIn=true;return this.account=account('1',false)},async logout(){this.signedIn=false;this.account=null},async refreshVerification(){return this.account=account()},
  async authorizedFetch(url,options={},verified){
   calls.push({url,options,verified,account:args.state()?.user?.app_user_id});assert.match(url,/^\/api\/auth\/identity-corrections(?:\/[1-9][0-9]*)?(?:\?after=[1-9][0-9]*&limit=25)?$/);
   const index=replies.findIndex(r=>(!r.match||url.includes(r.match))&&(!r.method||r.method===(options.method||'GET')));
   if(index>=0)return response(replies.splice(index,1)[0].value);
   assert.ok(!options.method||options.method==='GET','Every mutation needs a fixture');
   if(!url.split('?')[0].endsWith('/identity-corrections'))return response(defaultDetail);
   return response({items:defaultListings,next_after:null,can_write:true});
  }
 };
 const sessionStorage={getItem(key){if(storageDenied)throw Error('Denied storage');return storage.get(key)??null},setItem(key,value){if(storageDenied)throw Error('Denied storage');storage.set(key,value)},removeItem(key){if(storageDenied)throw Error('Denied storage');storage.delete(key)}};
 const context=vm.createContext({document,URL,URLSearchParams,Intl,Date,console,sessionStorage,location:{search:'',origin:'https://ygc.example'},CustomEvent:class{constructor(type){this.type=type}},YGCI18n:{t:(key,params={})=>key+(Object.keys(params).length?JSON.stringify(params):'')}});
 context.window=context;context.addEventListener=(key,fn)=>(listeners[key]??=[]).push(fn);
 vm.runInContext(fs.readFileSync(path.join(assets,'overlays.js'),'utf8'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-applications.js'),'utf8').split('export function createApplications')[0].replaceAll('export function','function'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-identity.js'),'utf8').replace(/^import .*;\n/gm,'').replaceAll('export function','function'),context);
 const create=context.createIdentityCorrections;context.createIdentityCorrections=value=>{args=value;component=create(value);return component};
 const noOp=()=>({render(){},clear(){},refresh:async()=>{},refreshHistory:async()=>{updates++},failed(){},setCatalogIntent(){}});
 Object.assign(context,{createFavorites:noOp,createVisibility:noOp,createDisputes:noOp,createNotifications:noOp,loadCloudAuth:async()=>client,createAvatar:noOp,createProfile:noOp,createGuitars:noOp,createClaims:noOp,createOwnership:noOp,createApplications:noOp,readCatalogIntent:()=>null,readClaimIntent:()=>null,readOwnershipIntent:()=>null});
 let ready;if(fullPage)ready=vm.runInContext('(async()=>{'+fs.readFileSync(path.join(assets,'cloud-account-page.js'),'utf8').replace(/^import .*;\n/gm,'')+'})()',context);else{component=context.createIdentityCorrections({auth:()=>client,state:()=>state,busy:()=>busy,work:async fn=>{busy=true;component.render();try{return await fn()}finally{busy=false;component.render()}},updated:async()=>{updates++}});ready=Promise.resolve()}
 const control=id=>ids.get(id);
 return {component,context,client,control,calls,storage,ready,get updates(){return updates},get dialog(){return control('identityDialog')},get list(){return control('identityListings')},get history(){return control('identityHistory')},
  queue(value,match=null,method=null){replies.push({value,match,method})},setDetail(value){defaultDetail=value},setListings(value){defaultListings=value},
  open(id='31'){return component.openListing(id)},create(){return control('identityCreate').onclick()},dismiss(){control('identityClose').onclick()},review(){return control('identityForm').onsubmit({preventDefault(){}})},confirm(){return control('identityConfirm').onclick()},
  changeAccount(next){state=next;client.signedIn=Boolean(next);component.render()},event(type){for(const fn of listeners[type]||[])fn({})},
  async flush(){for(let i=0;i<12;i++)await new Promise(resolve=>setImmediate(resolve))}
 };
}
const field=(e,id,value)=>{e.control(id).value=value;e.control(id).oninput?.()};
const writes=e=>e.calls.filter(c=>c.options.method==='POST');
async function compose(e){await e.component.refresh();await e.open();e.create();field(e,'identity_model','Corrected');field(e,'identityReason','Corrected typo');await e.review()}

for(const initial of [null,account('1',false),account('1',true,'banned'),account('1',true,'disabled')])test('Ineligible account has no private identity access or writes',async()=>{const e=environment({initial});await e.component.refresh();await e.open();e.create();await e.review();await e.confirm();assert.equal(e.calls.length,0);assert.equal(e.dialog.open,false)});

test('Authored Listing is available independently of current ownership and entry preserves original Listing',async()=>{const e=environment();await e.component.refresh();assert.match(e.list.textContent,/identity.edit_listing/);await e.list.children[0].children[2].onclick();assert.equal(e.dialog.open,true);assert.equal(e.control('identityForm').hidden,true);assert.equal(e.control('identityImmutable').textContent,'identity.immutable');assert.equal(e.control('identityImmediate').textContent,'identity.immediate');assert.match(e.control('identityListingDate').textContent,/2020-01-01/);e.create();assert.equal(e.control('identity_manufacturer').value,'Maker');assert.equal(e.control('identity_model').value,'Model');assert.equal(e.control('identity_year').value,'1965');assert.equal(e.control('identity_serial_number').value,'SERIAL-12');assert.equal(e.control('identity_finish'),undefined);assert.equal(e.control('identity_date'),undefined);assert.equal(writes(e).length,0)});

test('Current fields, revision-bound preview and explicit confirm create one positive correction',async()=>{const e=environment();await compose(e);assert.equal(writes(e).length,0);assert.match(e.control('identityPreview').textContent,/Model → Corrected/);assert.equal(e.control('identityConfirm').hidden,false);e.queue(success(),'/31','POST');const first=e.confirm();e.confirm();await first;assert.equal(writes(e).length,1);assert.deepEqual(JSON.parse(writes(e)[0].options.body),{revision:'a'.repeat(64),manufacturer:'Maker',model:'Corrected',year:'1965',serial_number:'SERIAL-12',reason:'Corrected typo'});for(const call of e.calls){assert.equal(call.verified,true);assert.equal(call.options.cache,'no-store');assert.equal(call.options.credentials,'omit');assert.equal(call.options.redirect,'error');assert.ok(!call.url.includes('viewer_id'))}assert.equal(e.control('identityForm').hidden,true);assert.match(e.history.textContent,/chronicle.positive/);assert.match(e.control('identityMessage').textContent,/identity.saved/);assert.equal(e.storage.size,0);assert.equal(e.updates,1)});

test('Changing a draft invalidates preview and cannot accidentally confirm old values',async()=>{const e=environment();await compose(e);field(e,'identity_model','Different');await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.control('identityConfirm').hidden,true);assert.equal(e.control('identityPreview').hidden,true)});

for(const change of [{identity_manufacturer:''},{identity_serial_number:''},{identity_model:'Model',identityReason:'reason only'},{identity_year:'x'.repeat(41)},{identity_model:'bad\u0000text'},{identityReason:'x'.repeat(2001)}])test('Invalid or no-op identity data cannot reach POST',async()=>{const e=environment();await compose(e);for(const [key,value] of Object.entries(change))field(e,key,value);await e.review();await e.confirm();assert.equal(writes(e).length,0);assert.match(e.control('identityMessage').textContent,/identity.invalid/)});

test('Review refetches current identity and forces a new preview after revision change',async()=>{const e=environment();await compose(e);e.setDetail(detail({revision:'b'.repeat(64),individual:guitar('12',{model:'New current'})}));await e.review();assert.equal(e.control('identityConfirm').hidden,true);assert.match(e.control('identityMessage').textContent,/identity.conflict/);await e.review();assert.match(e.control('identityPreview').textContent,/New current → Corrected/);assert.equal(e.control('identityConfirm').hidden,false)});

test('Confirmation never silently rebases an old preview to a fresh revision',async()=>{const e=environment();await compose(e);e.queue(detail({revision:'b'.repeat(64)}),'/31');await e.confirm();assert.equal(writes(e).length,0);assert.match(e.control('identityMessage').textContent,/identity.conflict/);assert.equal(e.control('identityConfirm').hidden,true)});

for(const interruption of ['close','back','pagehide','signout','other account','unverified','ban','disabled','input'])test('Held preflight followed by '+interruption+' never POSTs or revives',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/31');const job=e.confirm();if(interruption==='close')e.dismiss();else if(interruption==='back')e.event('popstate');else if(interruption==='pagehide')e.event('pagehide');else if(interruption==='input')field(e,'identity_model','New edit');else e.changeAccount(interruption==='signout'?null:account(interruption==='other account'?'2':'1',interruption!=='unverified',interruption==='ban'?'banned':interruption==='disabled'?'disabled':'active'));held.resolve(detail());await job;assert.equal(writes(e).length,0);if(interruption!=='input')assert.equal(e.dialog.open,false)});

for(const interruption of ['close','back','pagehide','signout','other account'])test('Held detail read after '+interruption+' cannot expose private values',async()=>{const e=environment(),held=deferred();e.queue(held.promise,'/31');const job=e.open();if(interruption==='close')e.dismiss();else if(interruption==='back')e.event('popstate');else if(interruption==='pagehide')e.event('pagehide');else e.changeAccount(interruption==='signout'?null:account('2'));held.resolve(detail());await job;assert.equal(e.dialog.open,false);assert.equal(e.control('identityGuitar').textContent,'');assert.equal(writes(e).length,0)});

for(const interruption of ['close','back','pagehide'])test('Successful POST after '+interruption+' refreshes list without reopening',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/31','POST');const job=e.confirm();await e.flush();assert.equal(writes(e).length,1);assert.equal(e.storage.size,1);if(interruption==='close')e.dismiss();else e.event(interruption==='back'?'popstate':'pagehide');held.resolve(success());await job;assert.equal(e.dialog.open,false);assert.equal(e.storage.size,0);assert.equal(e.updates,1)});

for(const interruption of ['signout','other account','ban','disabled'])test('Successful old-account POST after '+interruption+' cannot update current session',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/31','POST');const job=e.confirm();await e.flush();e.changeAccount(interruption==='signout'?null:account(interruption==='other account'?'2':'1',true,interruption==='ban'?'banned':interruption==='disabled'?'disabled':'active'));held.resolve(success());await job;assert.equal(e.dialog.open,false);assert.equal(e.list.children.length,0);assert.equal(e.storage.size,0);assert.equal(e.updates,0)});

for(const result of [Error('lost response with secret'),denied(500),denied(503),{},success({correction:{}}),success({correction:correction({target_claim_id:'99'})}),success({detail:detail({revision:'b'.repeat(64),items:[]})}),success({correction:correction({verification_status:'unverified'})})])test('Unknown or malformed result survives dismissal and requires history plus explicit acknowledgement',async()=>{const e=environment();await compose(e);e.queue(result,'/31','POST');await e.confirm();assert.equal(writes(e).length,1);assert.equal(e.control('identityReview').disabled,true);assert.equal(e.control('identityCheckSubmission').hidden,false);assert.equal(e.control('identityAcknowledge').hidden,true);e.dismiss();await e.open();assert.equal(e.control('identityCreate').disabled,true);assert.equal(e.control('identityAcknowledge').hidden,true);e.setDetail(success().detail);await e.control('identityCheckSubmission').onclick();assert.match(e.history.textContent,/#41/);assert.equal(e.control('identityAcknowledge').hidden,false);e.control('identityAcknowledge').onclick();assert.equal(e.control('identityCheckSubmission').hidden,true);assert.equal(e.control('identityForm').hidden,true);assert.equal(e.control('identityConfirm').hidden,true);assert.equal(e.storage.size,0);assert.equal(writes(e).length,1)});

test('Retry marker is saved before a POST can be lost during navigation or reload',async()=>{const e=environment(),held=deferred();await compose(e);e.queue(held.promise,'/31','POST');const job=e.confirm();await e.flush();assert.deepEqual(JSON.parse([...e.storage.values()][0]),{account:'uuid-1',ids:['31']});e.event('pagehide');const afterReload=environment({storage:e.storage});await afterReload.component.refresh();await afterReload.open();assert.equal(afterReload.control('identityCreate').disabled,true);assert.equal(afterReload.control('identityCheckSubmission').hidden,false);assert.equal(writes(afterReload).length,0);held.resolve(Error('lost'));await job;assert.match(e.control('identityStatus').textContent,/identity.uncertain/)});

test('Failed history check never enables acknowledgement or retry',async()=>{const e=environment();await compose(e);e.queue(Error('lost'),'/31','POST');await e.confirm();e.queue(Error('offline'),'/31');await e.control('identityCheckSubmission').onclick();e.control('identityAcknowledge').onclick();assert.equal(e.control('identityAcknowledge').hidden,true);assert.equal(e.control('identityReview').disabled,true);assert.equal(e.storage.size,1);assert.equal(writes(e).length,1)});

test('Reading history without using the explicit check does not unlock uncertain submission',async()=>{const e=environment();await compose(e);e.queue(Error('lost'),'/31','POST');await e.confirm();await e.control('identityReload').onclick();e.control('identityAcknowledge').onclick();assert.equal(e.control('identityAcknowledge').hidden,true);assert.equal(e.storage.size,1)});

for(const status of [400,409,422])test('Definitive rejection '+status+' discards confirmation without leaking raw error or duplicate ID',async()=>{const e=environment();await compose(e);e.queue(denied(status),'/31','POST');await e.confirm();assert.equal(e.storage.size,0);assert.equal(e.control('identityConfirm').hidden,true);assert.equal(e.control('identityCheckSubmission').hidden,true);assert.doesNotMatch(e.control('identityDialog').textContent,/SECRET|987654321/);await e.confirm();assert.equal(writes(e).length,1)});

for(const status of [401,403,404])test('Access rejection '+status+' purges private list/detail/inputs',async()=>{const e=environment();await compose(e);e.queue(denied(status),'/31','POST');await e.confirm();assert.equal(e.dialog.open,false);assert.equal(e.list.children.length,0);assert.equal(e.history.children.length,0);assert.equal(e.control('identityReason').value,'');assert.equal(e.control('identityGuitar').textContent,'');assert.equal(e.storage.size,0)});

for(const status of [403,503])test('Service-mode rejection '+status+' revalidates private read access before retaining history',async()=>{const e=environment();await compose(e);e.queue(detail(),'/31');e.queue(denied(status,'service_restricted'),'/31','POST');e.queue(detail({can_write:false}),'/31');await e.confirm();assert.equal(e.dialog.open,true);assert.equal(e.control('identityReview').disabled,true);assert.match(e.control('identityMessage').textContent,/applications.service_restricted/);assert.equal(e.storage.size,0)});

test('Service restriction followed by read denial removes previously loaded private detail',async()=>{const e=environment();await compose(e);e.queue(detail(),'/31');e.queue(denied(403,'service_restricted'),'/31','POST');e.queue(denied(403),'/31');await e.confirm();assert.equal(e.dialog.open,false);assert.equal(e.control('identityGuitar').textContent,'');assert.equal(e.list.children.length,0)});

for(const canWrite of [false,null,'true',undefined])test('Malformed or read-only write capability never permits creation',async()=>{const e=environment();e.setDetail(detail({can_write:canWrite}));await e.open();e.create();field(e,'identity_model','Corrected');await e.review();await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.control('identityCreate').disabled,true)});

test('Read-only preflight blocks the write and preserves private read-only review',async()=>{const e=environment();await compose(e);e.queue(detail({can_write:false}),'/31');await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.dialog.open,true);assert.equal(e.control('identityReview').disabled,true);assert.match(e.control('identityMessage').textContent,/identity.write_unavailable/)});

test('Unavailable session storage blocks mutation before it starts',async()=>{const e=environment({storageDenied:true});await compose(e);await e.confirm();assert.equal(writes(e).length,0);assert.match(e.control('identityMessage').textContent,/identity.storage_unavailable/);assert.equal(e.control('identityCheckSubmission').hidden,true)});

for(const raw of ['bad JSON','null','{"account":"uuid-2","ids":["31"]}','{"account":"uuid-1","ids":["01"]}','{"account":"uuid-1","ids":[31]}'])test('Malformed or another-account retry marker never grants access or blocks valid reads',async()=>{const storage=new Map([['ygc.identity-correction.uncertain.v1',raw]]),e=environment({storage});await e.open();assert.equal(e.control('identityCheckSubmission').hidden,true);assert.equal(storage.size,0);assert.equal(writes(e).length,0)});

test('Text-only rendering preserves literals without using innerHTML',async()=>{const e=environment();e.setListings([listing({individual:guitar('12',{model:'<img onerror=secret>'})})]);e.setDetail(detail({individual:guitar('12',{model:'<img onerror=secret>'}),items:[correction({body:'<script>secret</script>'})]}));await e.component.refresh();await e.open();assert.match(e.list.textContent,/<img/);assert.match(e.history.textContent,/<script>/);assert.equal(e.control('identityGuitar').children.length,0)});

for(const value of [detail({revision:'bad'}),detail({individual:guitar('13')}),detail({listing:{id:'99',individual_id:'12',occurred_at:null}}),detail({items:[correction({target_claim_id:'99'})]}),detail({items:[correction({changes:[{field_name:'finish',old_value:'a',new_value:'b'}]})]}),detail({items:[correction({changes:[{field_name:'model',old_value:'a',new_value:'a'}]})]}),detail({items:[correction(),correction()]}),detail({next_after:'41'}),detail({next_after:41}),detail({items:[correction({id:41})]})])test('Malformed private detail never enables correction',async()=>{const e=environment();e.setDetail(value);await e.open();e.create();await e.review();await e.confirm();assert.equal(e.control('identityCreate').disabled,true);assert.equal(e.control('identityGuitar').textContent,'');assert.equal(writes(e).length,0)});

test('Large Listing and history IDs stay exact across pagination and POST',async()=>{const id='9007199254740993',guitarId='9223372036854775807',e=environment(),large=detail({listing:{id,individual_id:guitarId,occurred_at:'2020-01-01'},individual:guitar(guitarId)});e.setListings([listing({id,individual:guitar(guitarId)})]);e.setDetail(large);await e.component.refresh();await e.open(id);e.create();field(e,'identity_model','Corrected');field(e,'identityReason','Corrected typo');await e.review();const row=correction({id:'9007199254740994',target_claim_id:id,individual_id:guitarId});e.queue({correction:row,detail:{...large,individual:guitar(guitarId,{model:'Corrected'}),items:[row],revision:'b'.repeat(64)}},'/'+id,'POST');await e.confirm();assert.equal(writes(e)[0].url,'/api/auth/identity-corrections/'+id);assert.match(e.history.textContent,/#9007199254740994/)});

test('Listing pagination and history pagination are bounded and validate decreasing exact cursors',async()=>{const e=environment();e.queue({items:[listing()],next_after:'31',can_write:true},'identity-corrections');await e.component.refresh();e.queue({items:[listing({id:'30'})],next_after:null,can_write:true},'after=31');await e.control('identityMore').onclick();assert.match(e.calls.at(-1).url,/after=31&limit=25$/);e.setDetail(detail({items:[correction()],next_after:'41'}));await e.open();e.queue(detail({items:[correction({id:'40'})],next_after:null}),'/31?after=41');await e.control('identityHistoryMore').onclick();assert.match(e.calls.at(-1).url,/after=41&limit=25$/);assert.match(e.history.textContent,/#41/);assert.match(e.history.textContent,/#40/)});

test('A changed history revision cannot append to or confirm against an older page',async()=>{const e=environment();e.setDetail(detail({items:[correction()],next_after:'41'}));await e.open();e.queue(detail({revision:'b'.repeat(64),items:[correction({id:'40'})]}),'/31?after=41');await e.control('identityHistoryMore').onclick();assert.doesNotMatch(e.history.textContent,/#40/);assert.match(e.control('identityMessage').textContent,/identity.conflict/)});

test('Newer list read supersedes old response',async()=>{const e=environment(),held=deferred();e.queue(held.promise,'identity-corrections');const job=e.component.refresh();e.setListings([listing({id:'50'})]);await e.component.refresh();held.resolve({items:[listing()],next_after:null,can_write:true});await job;assert.match(e.list.textContent,/50/);assert.doesNotMatch(e.list.textContent,/"id":"31"/)});

test('An older denied list request cannot clear a newly opened authorized detail',async()=>{const e=environment(),held=deferred();e.queue(held.promise,'identity-corrections');const job=e.component.refresh();await e.open();held.resolve(denied(403));await job;assert.equal(e.dialog.open,true);assert.match(e.control('identityGuitar').textContent,/SERIAL-12/)});

test('Account page restores Listings only after verification and clears on signout',async()=>{const e=environment({initial:null,fullPage:true});await e.ready;assert.equal(e.control('selfIdentityCorrections').hidden,true);await e.control('cloudAccountForm').onsubmit({preventDefault(){}});assert.equal(e.control('selfIdentityCorrections').hidden,true);await e.control('refreshVerification').onclick();assert.equal(e.control('selfIdentityCorrections').hidden,false);assert.match(e.list.textContent,/identity.edit_listing/);await e.open();e.create();field(e,'identityReason','PRIVATE');await e.control('signOut').onclick();assert.equal(e.dialog.open,false);assert.equal(e.control('selfIdentityCorrections').hidden,true);assert.equal(e.control('identityReason').value,'');assert.equal(writes(e).length,0)});

test('Positive older-Listing correction can return authoritative current snapshot from later chronology',async()=>{const e=environment();await compose(e);e.queue(success({detail:detail({individual:guitar('12',{model:'Later Listing current'}),items:[correction()],revision:'b'.repeat(64)})}),'/31','POST');await e.confirm();assert.equal(e.storage.size,0);assert.match(e.control('identityGuitar').textContent,/Later Listing current/);assert.match(e.history.textContent,/Model → Corrected/);assert.match(e.control('identityMessage').textContent,/identity.saved/)});

test('Undated Listing keeps its date null while correction uses server creation date fallback',async()=>{const e=environment(),original=detail({listing:{id:'31',individual_id:'12',occurred_at:null}});e.setDetail(original);await compose(e);const row=correction({occurred_at:'2026-10-07T01:00:00Z'});e.queue({correction:row,detail:{...original,items:[row],individual:guitar('12',{model:'Corrected'}),revision:'b'.repeat(64)}},'/31','POST');await e.confirm();assert.equal(e.storage.size,0);assert.match(e.control('identityMessage').textContent,/identity.saved/);assert.match(e.control('identityListingDate').textContent,/identity.empty_value/)});

for(const value of [detail({individual:guitar('12',{manufacturer:'x'.repeat(201)})}),detail({individual:guitar('12',{model:'bad\u0000model'})}),detail({individual:guitar('12',{model:'\ud800'})}),detail({items:[correction({body:'x'.repeat(2001)})]}),detail({items:[correction({created_at:'x'.repeat(41)})]}),detail({items:[correction({changes:[{field_name:'year',old_value:'x'.repeat(41),new_value:'2020'}]})]})])test('Oversized/control/malformed Unicode server fields fail closed without truncation',async()=>{const e=environment();e.setDetail(value);await e.open();assert.equal(e.control('identityGuitar').textContent,'');assert.equal(e.control('identityCreate').disabled,true);assert.equal(writes(e).length,0)});

test('Response text limits count Unicode code points without corrupting valid surrogate pairs',async()=>{const e=environment();e.setDetail(detail({individual:guitar('12',{model:'🎸'.repeat(200)})}));await e.open();assert.equal(e.control('identityCreate').disabled,false);assert.match(e.control('identityGuitar').textContent,/🎸/)});

test('Year-only edit preserves an existing maximum-valid Unicode model through preview and POST',async()=>{const e=environment(),model='🎸'.repeat(200),original=detail({individual:guitar('12',{model})});e.setDetail(original);await e.open();e.create();assert.equal(e.control('identity_model').value,model);assert.equal(e.control('identity_model').maxLength,400);assert.equal(e.control('identity_year').maxLength,80);field(e,'identity_year','1966');await e.review();assert.equal(e.control('identityConfirm').hidden,false);assert.match(e.control('identityPreview').textContent,/1965 → 1966/);const row=correction({body:null,changes:[{field_name:'year',old_value:'1965',new_value:'1966'}]});e.queue({correction:row,detail:{...original,individual:guitar('12',{model,year:'1966'}),revision:'b'.repeat(64),items:[row]}},'/31','POST');await e.confirm();assert.equal(writes(e).length,1);assert.equal(JSON.parse(writes(e)[0].options.body).model,model);assert.equal(e.storage.size,0);assert.match(e.control('identityMessage').textContent,/identity.saved/)});

test('Maximum-valid Unicode reason is preserved without clipping and can be submitted',async()=>{const e=environment(),reason='🎸'.repeat(2000);await compose(e);assert.equal(e.control('identityReason').maxLength,4000);field(e,'identityReason',reason);await e.review();assert.equal(e.control('identityConfirm').hidden,false);const row=correction({body:reason});e.queue(success({correction:row,detail:detail({individual:guitar('12',{model:'Corrected'}),revision:'b'.repeat(64),items:[row]})}),'/31','POST');await e.confirm();assert.equal(writes(e).length,1);assert.equal(JSON.parse(writes(e)[0].options.body).reason,reason);assert.equal(e.storage.size,0)});

for(const [id,value] of [['identity_model','🎸'.repeat(201)],['identity_year','🎸'.repeat(41)],['identityReason','🎸'.repeat(2001)],['identity_model','\ud800'],['identityReason','\udfff']])test('Over-bound or malformed Unicode draft is rejected using the server code-point limits',async()=>{const e=environment();await compose(e);field(e,id,value);await e.review();await e.confirm();assert.equal(writes(e).length,0);assert.equal(e.control('identityConfirm').hidden,true);assert.match(e.control('identityMessage').textContent,/identity.invalid/)});
