const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const assets=path.join(__dirname,'../src/ygc/static');
const account=(id='1',verified=true,status='active')=>({user:{app_user_id:'uuid-'+id,display_name:'Member '+id,role:'member',status},identity:{email_verified:verified}});
const row=(extra={})=>({id:'9007199254741009',notification_type:'transfer_request',title:'Historical request',body:'Private notice body',created_at:'2026-10-07T01:00:00Z',is_read:false,read_at:null,actor:{id:'9007199254741001',display_name:'Sender'},destination:{kind:'transfer',claim_id:'9007199254741005'},...extra});
const page=(extra={})=>({items:[row()],next_after:null,unread_count:'1',can_write:true,...extra});
const success=(extra={})=>({id:row().id,is_read:true,read_at:'2026-10-07T02:00:00Z',unread_count:'0',...extra});
const denied=(status=403,code='account_inactive')=>({httpStatus:status,code});
const deferred=()=>{let resolve;const promise=new Promise(r=>{resolve=r});return {promise,resolve}};
function environment({initial=account(),fullPage=false}={}){
 const ids=new Map(),listeners={};
 class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.dataset={};this.style={};this.value='';this.hidden=false;this.open=false;this.disabled=false;this._text='';this.classList={add(){},remove(){}};this.isConnected=true;this.tabIndex=0}
  set id(value){this._id=value;ids.set(value,this)}get id(){return this._id}
  set textContent(value){this._text=String(value);this.children=[]}get textContent(){return this._text+this.children.map(n=>n.textContent).join('')}
  set innerHTML(value){throw Error('Notifications must be text-only')}
  append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this._text='';this.children=nodes}
  setAttribute(key,value){this[key]=value}removeAttribute(key){delete this[key]}hasAttribute(key){return key in this}
  addEventListener(key,fn){(this.listeners[key]??=[]).push(fn)}dispatchEvent(event){for(const fn of this.listeners[event.type]||[])fn(event)}
  all(){return this.children.flatMap(n=>[n,...n.all()])}contains(n){return n===this||this.all().includes(n)}
  querySelectorAll(selector){return this.all().filter(n=>selector.split(',').map(t=>t.toUpperCase()).includes(n.tagName))}querySelector(s){return this.querySelectorAll(s)[0]||null}
  reset(){for(const n of this.all())n.value=''}focus(){document.activeElement=this}closest(){return null}getClientRects(){return this.hidden?[]:[this.getBoundingClientRect()]}
  getBoundingClientRect(){return {left:20,right:600,top:20,bottom:600}}showModal(){this.open=true}close(){this.open=false}
 }
 const document={body:new Element('body'),documentElement:{lang:'en'},createElement:tag=>new Element(tag),getElementById:id=>ids.get(id),addEventListener(key,fn){(listeners[key]??=[]).push(fn)}};
 for(const match of fs.readFileSync(path.join(assets,'cloud_account_html.html'),'utf8').matchAll(/<(\w+)[^>]*\bid="([^"]+)"/g)){const n=new Element(match[1]);n.id=match[2];document.body.append(n)}
 let state=initial,busy=false,component,args,defaultPage=page(),logoutResult=null;const calls=[],replies=[],opened=[];
 async function response(value){const data=await value;if(data instanceof Error)throw data;return data?.httpStatus?{ok:false,status:data.httpStatus,json:async()=>({detail:{code:data.code,message:'SECRET SQL / private@example.invalid'}})}:{ok:true,json:async()=>data}}
 const client={signedIn:Boolean(initial),account:initial,documents:async()=>({terms:{version:'t'},privacy:{version:'p'}}),restore:async()=>initial,
  async signIn(){this.signedIn=true;return this.account=account('1',false)},async logout(){await logoutResult;this.signedIn=false;this.account=null},async refreshVerification(){return this.account=account()},
  async authorizedFetch(url,options={},verified){
   calls.push({url,options,verified,account:args.state()?.user?.app_user_id});
   const index=replies.findIndex(r=>(!r.match||url.includes(r.match))&&(!r.method||r.method===(options.method||'GET')));
   if(index>=0)return response(replies.splice(index,1)[0].value);
   assert.ok(!options.method||options.method==='GET','Every mutation needs an explicit fixture');
   assert.match(url,/^\/api\/auth\/notifications(?:\?(?:after=[1-9][0-9]*&)?limit=25)?$/);return response(defaultPage);
  }
 };
 const context=vm.createContext({document,URL,URLSearchParams,Intl,Date,console,location:{search:'',origin:'https://ygc.example'},CustomEvent:class{constructor(type){this.type=type}},YGCI18n:{t:(key,params={})=>key+(Object.keys(params).length?JSON.stringify(params):'')}});
 context.window=context;context.addEventListener=(key,fn)=>(listeners[key]??=[]).push(fn);
 vm.runInContext(fs.readFileSync(path.join(assets,'overlays.js'),'utf8'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-applications.js'),'utf8').split('export function createApplications')[0].replaceAll('export function','function'),context);
 vm.runInContext(fs.readFileSync(path.join(assets,'cloud-account-notifications.js'),'utf8').replace(/^import .*;\n/gm,'').replaceAll('export function','function'),context);
 const create=context.createNotifications;context.createNotifications=value=>{args=value;component=create(value);return component};
 const openTransfer=async id=>{opened.push(['transfer',id]);return client.authorizedFetch('/api/auth/transfers/'+id,{cache:'no-store',credentials:'omit',redirect:'error'},true)};
 const openOwner=async(id,claim)=>{opened.push(['owner',id,claim]);return client.authorizedFetch('/api/auth/guitars/'+id+'/owner-responses',{cache:'no-store',credentials:'omit',redirect:'error'},true)};
 const openDispute=async id=>{opened.push(['dispute',id]);return client.authorizedFetch('/api/auth/ownership-disputes/'+id,{cache:'no-store',credentials:'omit',redirect:'error'},true)};
 const openDisputeOption=async id=>{opened.push(['dispute_option',id]);return client.authorizedFetch('/api/auth/ownership-disputes/options/'+id,{cache:'no-store',credentials:'omit',redirect:'error'},true)};
 const noOp=()=>({render(){},clear(){},refresh:async()=>{},refreshHistory:async()=>{},failed(){},setCatalogIntent(){},openGuitar(){},openTransfer,openOwner,openDispute,openDisputeOption});
 Object.assign(context,{loadCloudAuth:async()=>client,createAvatar:noOp,createProfile:noOp,createGuitars:noOp,createClaims:noOp,createOwnership:noOp,createApplications:noOp,createDisputes:noOp,createIdentityCorrections:noOp,readCatalogIntent:()=>null,readClaimIntent:()=>null,readOwnershipIntent:()=>null});
 let ready;if(fullPage)ready=vm.runInContext('(async()=>{'+fs.readFileSync(path.join(assets,'cloud-account-page.js'),'utf8').replace(/^import .*;\n/gm,'')+'})()',context);else{component=context.createNotifications({auth:()=>client,state:()=>state,busy:()=>busy,work:async fn=>{busy=true;component.render();try{return await fn()}finally{busy=false;component.render()}},openTransfer,openOwner,openDispute,openDisputeOption});ready=Promise.resolve()}
 const control=id=>ids.get(id),buttons=()=>control('notificationList').querySelectorAll('button');
 return {component,context,client,control,calls,opened,ready,get list(){return control('notificationList')},
  queue(value,match=null,method=null){replies.push({value,match,method})},setPage(value){defaultPage=value},holdLogout(value){logoutResult=value},
  mark(){return buttons().find(n=>n.dataset.notificationMark)?.onclick()},open(){return buttons().find(n=>n.dataset.notificationOpen)?.onclick()},
  changeAccount(next){state=next;client.signedIn=Boolean(next);component.render()},event(type){for(const fn of listeners[type]||[])fn({})},
  async flush(){for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve))}
 };
}
const writes=e=>e.calls.filter(call=>call.options.method==='POST');
const markButton=e=>e.list.querySelectorAll('button').find(n=>n.dataset.notificationMark);

for(const initial of [null,account('1',false),account('1',true,'banned'),account('1',true,'disabled')])test('Ineligible session cannot read or mutate the inbox',async()=>{const e=environment({initial});await e.component.refresh();await e.control('notificationMarkAll').onclick();assert.equal(e.calls.length,0);assert.equal(e.control('selfNotifications').hidden,true)});

test('Initial load keeps exact BIGINT strings and reads without side effects',async()=>{const e=environment();await e.component.refresh();assert.match(e.list.textContent,/Historical request/);assert.match(e.control('notificationUnread').textContent,/"1"/);assert.equal(e.list.children[0].dataset.notificationId,row().id);assert.equal(writes(e).length,0);assert.match(e.calls[0].url,/limit=25$/);for(const call of e.calls){assert.equal(call.verified,true);assert.equal(call.options.cache,'no-store');assert.equal(call.options.credentials,'omit');assert.equal(call.options.redirect,'error');assert.doesNotMatch(call.url,/recipient|viewer|user_id/)}});

test('Mark one is explicit, duplicate-click safe, and rereads only this inbox',async()=>{const e=environment();await e.component.refresh();e.queue(success(),'/read','POST');e.setPage(page({items:[row({is_read:true,read_at:success().read_at})],unread_count:'0'}));const first=e.mark();e.mark();await first;assert.equal(writes(e).length,1);assert.equal(writes(e)[0].url,'/api/auth/notifications/'+row().id+'/read');assert.equal(writes(e)[0].options.body,'{}');assert.equal(markButton(e).hidden,true);assert.equal(e.opened.length,0);assert.match(e.list.textContent,/2026-10-07T02/);assert.equal(e.control('notificationMarkAll').disabled,true)});

test('Mark all never resolves a Transfer or acknowledges an ownership decline',async()=>{const e=environment();e.setPage(page({items:[row({notification_type:'ownership_decline',destination:null})]}));await e.component.refresh();e.queue({marked_count:'1',unread_count:'0'},'/read-all','POST');e.setPage(page({items:[row({notification_type:'ownership_decline',destination:null,is_read:true,read_at:success().read_at})],unread_count:'0'}));await e.control('notificationMarkAll').onclick();assert.deepEqual(writes(e).map(c=>c.url),['/api/auth/notifications/read-all']);assert.equal(e.opened.length,0);assert.equal(e.list.querySelectorAll('button').filter(n=>n.dataset.notificationOpen).length,0)});

for(const target of [{kind:'transfer',claim_id:'9223372036854775807'},{kind:'owner',individual_id:'9007199254740993',claim_id:'9223372036854775807'}])test('Supported destination uses an existing canonical current-access GET and never marks read',async()=>{const e=environment();e.setPage(page({items:[row({destination:target})]}));await e.component.refresh();e.queue({},target.kind==='transfer'?'/transfers/':'/owner-responses');await e.open();assert.equal(e.opened.length,1);assert.equal(writes(e).length,0);assert.equal(markButton(e).hidden,false);assert.match(e.calls.at(-1).url,target.kind==='transfer'?/\/transfers\/9223372036854775807$/:/\/guitars\/9007199254740993\/owner-responses$/)});

test('Unsupported historical notices show plaintext without invented local/public/profile/photo links',async()=>{const e=environment();e.setPage(page({items:[row({notification_type:'dispute_result',destination:null,body:'<a href="/api/disputes/1">Private</a>'})]}));await e.component.refresh();assert.match(e.list.textContent,/<a href=/);assert.equal(e.list.querySelectorAll('a,img').length,0);assert.equal(e.list.querySelectorAll('button').length,1);assert.equal(writes(e).length,0)});

test('Untrusted title, body, actor, and date stay text-only',async()=>{const e=environment();const attack='<img src=x onerror=secret>';e.setPage(page({items:[row({title:attack,body:attack,actor:{id:'1',display_name:attack},created_at:'<script>secret</script>'})]}));await e.component.refresh();assert.match(e.list.textContent,/<img/);assert.equal(e.list.querySelectorAll('img,script,a').length,0);assert.equal(e.list.children[0].children[0].children.length,0)});

test('Large unread count remains exact without Number coercion',async()=>{const e=environment();e.setPage(page({unread_count:'9223372036854775807'}));await e.component.refresh();assert.match(e.control('notificationUnread').textContent,/9223372036854775807/)});

test('Next and Previous page in descending exact-ID order with a bounded cursor',async()=>{const e=environment();e.setPage(page({next_after:row().id}));await e.component.refresh();e.queue(page({items:[row({id:'9007199254741008'})]}),'after=');await e.control('notificationNext').onclick();assert.equal(e.list.children.length,1);assert.equal(e.list.children[0].dataset.notificationId,'9007199254741008');assert.equal(e.control('notificationPrevious').disabled,false);assert.match(e.calls.at(-1).url,/after=9007199254741009&limit=25$/);await e.control('notificationPrevious').onclick();assert.equal(e.list.children[0].dataset.notificationId,row().id);assert.equal(e.control('notificationPrevious').disabled,true)});

test('Read-only preserves browsing and current-target reads while disabling both read mutations',async()=>{const e=environment();e.setPage(page({can_write:false}));await e.component.refresh();assert.equal(markButton(e).disabled,true);assert.equal(e.control('notificationMarkAll').disabled,true);await e.mark();await e.control('notificationMarkAll').onclick();e.queue({},'/transfers/');await e.open();assert.equal(writes(e).length,0);assert.equal(e.opened.length,1);assert.match(e.control('notificationStatus').textContent,/applications.read_only/)});

for(const interruption of ['signout','account','unverified','ban','disabled','popstate','pagehide'])test('Pending list response after '+interruption+' cannot restore private rows or count',async()=>{const e=environment(),held=deferred();await e.component.refresh();const oldMark=markButton(e).onclick,oldOpen=e.list.querySelectorAll('button').find(n=>n.dataset.notificationOpen).onclick;e.queue(held.promise);const job=e.component.refresh();if(['popstate','pagehide'].includes(interruption))e.event(interruption);else e.changeAccount(interruption==='signout'?null:account(interruption==='account'?'2':'1',interruption!=='unverified',interruption==='ban'?'banned':interruption==='disabled'?'disabled':'active'));held.resolve(page());await job;assert.equal(e.list.children.length,0);assert.equal(e.control('notificationUnread').textContent,'');await oldMark();await oldOpen();assert.equal(writes(e).length,0);assert.equal(e.opened.length,0)});

for(const interruption of ['signout','account','popstate','pagehide'])test('Late read-update response after '+interruption+' cannot reload private data',async()=>{const e=environment(),held=deferred();await e.component.refresh();e.queue(held.promise,'/read','POST');const job=e.mark();await e.flush();assert.equal(writes(e).length,1);if(['popstate','pagehide'].includes(interruption))e.event(interruption);else e.changeAccount(interruption==='signout'?null:account('2'));const count=e.calls.length;held.resolve(success());await job;assert.equal(e.calls.length,count);assert.equal(e.list.children.length,0);assert.equal(e.control('notificationUnread').textContent,'')});

test('Newer list wins over a delayed old success or access denial',async()=>{for(const value of [page(),denied(403)]){const e=environment(),held=deferred();e.queue(held.promise);const job=e.component.refresh();e.setPage(page({items:[row({title:'Latest notice'})],unread_count:'2'}));await e.component.refresh();held.resolve(value);await job;assert.match(e.list.textContent,/Latest notice/);assert.match(e.control('notificationUnread').textContent,/"2"/)}});

test('A late write result cannot override a newer explicitly refreshed page',async()=>{const e=environment(),held=deferred();await e.component.refresh();e.queue(held.promise,'/read','POST');const job=e.mark();await e.flush();e.setPage(page({items:[row({title:'Newer state'})]}));await e.component.refresh();const count=e.calls.length;held.resolve(success());await job;assert.equal(e.calls.length,count);assert.match(e.list.textContent,/Newer state/)});

for(const value of [Error('Lost response SECRET'),denied(500),denied(503),{},success({id:'3'}),success({is_read:false}),success({read_at:null}),success({unread_count:0}),success({private_email:'secret@example.invalid'})])test('Unknown or malformed read outcome blocks all mutations until an explicit successful refresh',async()=>{const e=environment();await e.component.refresh();e.queue(value,'/read','POST');await e.mark();assert.equal(writes(e).length,1);assert.equal(markButton(e).disabled,true);assert.equal(e.control('notificationMarkAll').disabled,true);assert.match(e.control('notificationStatus').textContent,/notifications.uncertain/);await e.mark();await e.control('notificationMarkAll').onclick();assert.equal(writes(e).length,1);e.queue(denied(503));await e.control('notificationRefresh').onclick();assert.equal(e.control('notificationMarkAll').disabled,true);await e.control('notificationRefresh').onclick();assert.equal(markButton(e).disabled,false);assert.equal(writes(e).length,1);assert.doesNotMatch(e.control('notificationStatus').textContent,/SECRET/)});

for(const status of [401,403,404])test('Definitive access rejection '+status+' clears rows and unread badge',async()=>{const e=environment();await e.component.refresh();e.queue(denied(status),'/read','POST');await e.mark();assert.equal(e.list.children.length,0);assert.equal(e.control('notificationUnread').textContent,'');assert.doesNotMatch(e.control('notificationStatus').textContent,/SECRET|SQL|private@example/)});

for(const status of [400,409,422])test('Definitive update rejection '+status+' requires a fresh read before another explicit click',async()=>{const e=environment();await e.component.refresh();e.queue(denied(status),'/read','POST');await e.mark();await e.mark();assert.equal(writes(e).length,1);assert.equal(markButton(e).disabled,true);assert.doesNotMatch(e.control('notificationStatus').textContent,/notifications.uncertain/);await e.control('notificationRefresh').onclick();assert.equal(markButton(e).disabled,false)});

test('Service-mode write denial rereads current access and keeps only read-only contents',async()=>{const e=environment();await e.component.refresh();e.queue(denied(403,'service_restricted'),'/read','POST');e.setPage(page({can_write:false}));await e.mark();assert.equal(e.list.children.length,1);assert.equal(markButton(e).disabled,true);assert.match(e.control('notificationStatus').textContent,/service_restricted/);assert.equal(writes(e).length,1)});

test('Service-mode read denial after a write denial purges everything private',async()=>{const e=environment();await e.component.refresh();e.queue(denied(403,'service_restricted'),'/read','POST');e.queue(denied(403),'limit=25');await e.mark();assert.equal(e.list.children.length,0);assert.equal(e.control('notificationUnread').textContent,'')});

const badRows=[row({id:9007199254741009}),row({id:'01'}),row({id:'9223372036854775808'}),row({actor:{id:1,display_name:'a'}}),row({actor:{id:'1',display_name:'a',email:'secret'}}),row({destination:{kind:'dispute',claim_id:'1'}}),row({destination:{kind:'transfer',claim_id:'1',url:'https://evil.invalid'}}),row({destination:{kind:'owner',individual_id:'01',claim_id:'1'}}),row({title:'x'.repeat(201)}),row({body:'x'.repeat(8001)}),row({notification_type:'x'.repeat(65)}),row({actor:{id:'1',display_name:'x'.repeat(121)}}),row({title:'bad\0title'}),row({body:'bad\u0007body'}),row({title:'\ud800'}),row({body:'\udfff'}),row({created_at:'x'.repeat(41)}),row({is_read:0}),row({body:1}),row({extra:'secret'}),row({actor:undefined})];
for(const value of badRows)test('Malformed, oversized, or unallowlisted row is rejected without display',async()=>{const e=environment();e.setPage(page({items:[value]}));await e.component.refresh();assert.equal(e.list.children.length,0);assert.equal(e.control('notificationUnread').textContent,'');assert.equal(e.control('notificationMarkAll').disabled,true)});
for(const value of [page({can_write:'true'}),page({unread_count:1}),page({unread_count:'01'}),page({unread_count:'9223372036854775808'}),page({next_after:row().id,items:[]}),page({next_after:'3'}),page({next_after:3}),page({items:[row(),row()]}),page({items:[row({id:'1'}),row({id:'2'})]}),page({items:Array.from({length:26},(_,i)=>row({id:String(100-i)}))}),page({private_key:'secret'})])test('Malformed page, count, size, or cursor fails closed',async()=>{const e=environment();e.setPage(value);await e.component.refresh();assert.equal(e.list.children.length,0);assert.equal(e.control('notificationUnread').textContent,'');assert.equal(writes(e).length,0)});

test('Pagination rejects repeated or increasing IDs relative to the requested cursor',async()=>{const e=environment();e.setPage(page({next_after:row().id}));await e.component.refresh();e.queue(page(),'after=');await e.control('notificationNext').onclick();assert.equal(e.list.children.length,0);assert.equal(e.control('notificationNext').disabled,true)});

test('Valid maximum Unicode strings use code-point limits and retain line breaks',async()=>{const e=environment();e.setPage(page({items:[row({title:'🎸'.repeat(200),body:'🎸'.repeat(7998)+'\n\t',actor:{id:'1',display_name:'🎸'.repeat(120)}})]}));await e.component.refresh();assert.equal(e.list.children.length,1);assert.match(e.list.textContent,/🎸/)});

test('Empty inbox has zero badge and disabled mutations and navigation',async()=>{const e=environment();e.setPage(page({items:[],unread_count:'0'}));await e.component.refresh();assert.equal(e.list.children.length,0);for(const id of ['notificationMarkAll','notificationNext','notificationPrevious'])assert.equal(e.control(id).disabled,true);assert.match(e.control('notificationStatus').textContent,/notifications.empty/)});

test('Account shell only loads a verified inbox and clears immediately before delayed logout',async()=>{const e=environment({initial:null,fullPage:true});await e.ready;assert.equal(e.control('selfNotifications').hidden,true);await e.control('cloudAccountForm').onsubmit({preventDefault(){}});assert.equal(e.control('selfNotifications').hidden,true);await e.control('refreshVerification').onclick();assert.equal(e.list.children.length,1);const held=deferred();e.holdLogout(held.promise);const job=e.control('signOut').onclick();assert.equal(e.list.children.length,0);assert.equal(e.control('notificationUnread').textContent,'');held.resolve();await job;assert.equal(e.control('selfNotifications').hidden,true);assert.equal(writes(e).length,0)});

test('Existing destination components retain canonical read entrypoints and target checks',()=>{const ownership=fs.readFileSync(path.join(assets,'cloud-account-ownership.js'),'utf8'),guitars=fs.readFileSync(path.join(assets,'cloud-account-guitars.js'),'utf8');assert.match(ownership,/setCatalogIntent,openGuitar,openTransfer/);assert.match(ownership,/const row=await readTransfer\(id\)/);assert.match(guitars,/refreshHistory,clear,openOwner/);assert.match(guitars,/await ownerRequest\(id\+'\/owner-responses'\)/);assert.match(guitars,/claimId!==null&&!result.items.some\(row=>row.id===claimId\)/)});

test('Legacy null body renders as empty text without rejecting the inbox',async()=>{const e=environment();e.setPage(page({items:[row({body:null})]}));await e.component.refresh();assert.equal(e.list.children.length,1);assert.equal(e.list.children[0].children[1].textContent,'');assert.doesNotMatch(e.list.textContent,/null/)});

for(const outcome of [denied(400),denied(409),denied(422),Error('Unknown read outcome')])test('Read-update failure keeps supported target controls functional through fresh canonical reads while marks stay disabled',async()=>{const e=environment();await e.component.refresh();e.queue(outcome,'/read','POST');await e.mark();const open=e.list.querySelectorAll('button').find(n=>n.dataset.notificationOpen);assert.equal(open.disabled,false);assert.equal(markButton(e).disabled,true);e.queue({},'/transfers/');await open.onclick();assert.equal(e.opened.length,1);assert.match(e.calls.at(-1).url,/\/transfers\//);assert.equal(writes(e).length,1)});
for(const target of [{kind:'dispute',case_id:'9223372036854775807'},{kind:'dispute_option',claim_id:'9007199254740993'}])test('Private dispute notice opens only a fresh authorized exact-ID read without accepting or marking read',async()=>{const e=environment();e.setPage(page({items:[row({destination:target})]}));await e.component.refresh();e.queue({},'/ownership-disputes/');await e.open();assert.equal(e.opened.length,1);assert.equal(e.opened[0][0],target.kind);assert.equal(writes(e).length,0);assert.equal(markButton(e).hidden,false);assert.match(e.calls.at(-1).url,target.kind==='dispute'?/\/ownership-disputes\/9223372036854775807$/:/\/ownership-disputes\/options\/9007199254740993$/);assert.equal(e.calls.at(-1).options.credentials,'omit');assert.equal(e.calls.at(-1).verified,true)});
